                                    DATA DICTIONARY
                                    
    1. ORIGINAL DATASET: Human Activity Recognition Using Smartphones Dataset
        1.1. Data description
        1.2. Original variables
        1.3. Original datasets
        1.4. Final notes
    2. TIDY DATASET: Merged information with activity and variables labels
        2.1. Transformations made to the original dataset
        2.2. Variables
        2.3. Units
        2.4. Final tidy_data
    3. INDEPENDENT TIDY DATASET: Average of each measurement variable by subject and activity
        3.1. Transformations made to the tidy_data set
        3.2. Variables
        3.3. Units
        3.4. Final ind_tidy_data
    4. FOR MORE INFORMATION

1. ORIGINAL DATASET: Human Activity Recognition Using Smartphones Dataset
-------------------------------------------------------------------------

### 1.1. Data description

The following is the original description of the "Human Activity
Recognition Using Smartphones Dataset" features.

**Source: *"features\_info.txt"* file from**
<https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip>

The features selected for this database come from the accelerometer and
gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain
signals (prefix 't' to denote time) were captured at a constant rate of
50 Hz. Then they were filtered using a median filter and a 3rd order low
pass Butterworth filter with a corner frequency of 20 Hz to remove
noise. Similarly, the acceleration signal was then separated into body
and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ)
using another low pass Butterworth filter with a corner frequency of 0.3
Hz.

Subsequently, the body linear acceleration and angular velocity were
derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and
tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional
signals were calculated using the Euclidean norm (tBodyAccMag,
tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag).

Finally a Fast Fourier Transform (FFT) was applied to some of these
signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ,
fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to
indicate frequency domain signals).

These signals were used to estimate variables of the feature vector for
each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

-   tBodyAcc-XYZ
-   tGravityAcc-XYZ
-   tBodyAccJerk-XYZ
-   tBodyGyro-XYZ
-   tBodyGyroJerk-XYZ
-   tBodyAccMag
-   tGravityAccMag
-   tBodyAccJerkMag
-   tBodyGyroMag
-   tBodyGyroJerkMag
-   fBodyAcc-XYZ
-   fBodyAccJerk-XYZ
-   fBodyGyro-XYZ
-   fBodyAccMag
-   fBodyAccJerkMag
-   fBodyGyroMag
-   fBodyGyroJerkMag

The set of variables that were estimated from these signals are:

-   mean(): Mean value
-   std(): Standard deviation
-   mad(): Median absolute deviation
-   max(): Largest value in array
-   min(): Smallest value in array
-   sma(): Signal magnitude area
-   energy(): Energy measure. Sum of the squares divided by the number
    of values.
-   iqr(): Interquartile range
-   entropy(): Signal entropy
-   arCoeff(): Autorregresion coefficients with Burg order equal to 4
-   correlation(): correlation coefficient between two signals
-   maxInds(): index of the frequency component with largest magnitude
-   meanFreq(): Weighted average of the frequency components to obtain a
    mean frequency
-   skewness(): skewness of the frequency domain signal
-   kurtosis(): kurtosis of the frequency domain signal
-   bandsEnergy(): Energy of a frequency interval within the 64 bins of
    the FFT of each window.
-   angle(): Angle between to vectors.

Additional vectors obtained by averaging the signals in a signal window
sample. These are used on the angle() variable:

-   gravityMean
-   tBodyAccMean
-   tBodyAccJerkMean
-   tBodyGyroMean
-   tBodyGyroJerkMean

### 1.2. Original variables

The complete list of variables of each feature vector is available in
*"features.txt"*, as shown here:

**Source: *"features.txt"* file from**
<https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip>

    ## [1] "RUN: features"

    ##      V1                                   V2
    ## 1     1                    tBodyAcc-mean()-X
    ## 2     2                    tBodyAcc-mean()-Y
    ## 3     3                    tBodyAcc-mean()-Z
    ## 4     4                     tBodyAcc-std()-X
    ## 5     5                     tBodyAcc-std()-Y
    ## 6     6                     tBodyAcc-std()-Z
    ## 7     7                     tBodyAcc-mad()-X
    ## 8     8                     tBodyAcc-mad()-Y
    ## 9     9                     tBodyAcc-mad()-Z
    ## 10   10                     tBodyAcc-max()-X
    ## 11   11                     tBodyAcc-max()-Y
    ## 12   12                     tBodyAcc-max()-Z
    ## 13   13                     tBodyAcc-min()-X
    ## 14   14                     tBodyAcc-min()-Y
    ## 15   15                     tBodyAcc-min()-Z
    ## 16   16                       tBodyAcc-sma()
    ## 17   17                  tBodyAcc-energy()-X
    ## 18   18                  tBodyAcc-energy()-Y
    ## 19   19                  tBodyAcc-energy()-Z
    ## 20   20                     tBodyAcc-iqr()-X
    ## 21   21                     tBodyAcc-iqr()-Y
    ## 22   22                     tBodyAcc-iqr()-Z
    ## 23   23                 tBodyAcc-entropy()-X
    ## 24   24                 tBodyAcc-entropy()-Y
    ## 25   25                 tBodyAcc-entropy()-Z
    ## 26   26               tBodyAcc-arCoeff()-X,1
    ## 27   27               tBodyAcc-arCoeff()-X,2
    ## 28   28               tBodyAcc-arCoeff()-X,3
    ## 29   29               tBodyAcc-arCoeff()-X,4
    ## 30   30               tBodyAcc-arCoeff()-Y,1
    ## 31   31               tBodyAcc-arCoeff()-Y,2
    ## 32   32               tBodyAcc-arCoeff()-Y,3
    ## 33   33               tBodyAcc-arCoeff()-Y,4
    ## 34   34               tBodyAcc-arCoeff()-Z,1
    ## 35   35               tBodyAcc-arCoeff()-Z,2
    ## 36   36               tBodyAcc-arCoeff()-Z,3
    ## 37   37               tBodyAcc-arCoeff()-Z,4
    ## 38   38           tBodyAcc-correlation()-X,Y
    ## 39   39           tBodyAcc-correlation()-X,Z
    ## 40   40           tBodyAcc-correlation()-Y,Z
    ## 41   41                 tGravityAcc-mean()-X
    ## 42   42                 tGravityAcc-mean()-Y
    ## 43   43                 tGravityAcc-mean()-Z
    ## 44   44                  tGravityAcc-std()-X
    ## 45   45                  tGravityAcc-std()-Y
    ## 46   46                  tGravityAcc-std()-Z
    ## 47   47                  tGravityAcc-mad()-X
    ## 48   48                  tGravityAcc-mad()-Y
    ## 49   49                  tGravityAcc-mad()-Z
    ## 50   50                  tGravityAcc-max()-X
    ## 51   51                  tGravityAcc-max()-Y
    ## 52   52                  tGravityAcc-max()-Z
    ## 53   53                  tGravityAcc-min()-X
    ## 54   54                  tGravityAcc-min()-Y
    ## 55   55                  tGravityAcc-min()-Z
    ## 56   56                    tGravityAcc-sma()
    ## 57   57               tGravityAcc-energy()-X
    ## 58   58               tGravityAcc-energy()-Y
    ## 59   59               tGravityAcc-energy()-Z
    ## 60   60                  tGravityAcc-iqr()-X
    ## 61   61                  tGravityAcc-iqr()-Y
    ## 62   62                  tGravityAcc-iqr()-Z
    ## 63   63              tGravityAcc-entropy()-X
    ## 64   64              tGravityAcc-entropy()-Y
    ## 65   65              tGravityAcc-entropy()-Z
    ## 66   66            tGravityAcc-arCoeff()-X,1
    ## 67   67            tGravityAcc-arCoeff()-X,2
    ## 68   68            tGravityAcc-arCoeff()-X,3
    ## 69   69            tGravityAcc-arCoeff()-X,4
    ## 70   70            tGravityAcc-arCoeff()-Y,1
    ## 71   71            tGravityAcc-arCoeff()-Y,2
    ## 72   72            tGravityAcc-arCoeff()-Y,3
    ## 73   73            tGravityAcc-arCoeff()-Y,4
    ## 74   74            tGravityAcc-arCoeff()-Z,1
    ## 75   75            tGravityAcc-arCoeff()-Z,2
    ## 76   76            tGravityAcc-arCoeff()-Z,3
    ## 77   77            tGravityAcc-arCoeff()-Z,4
    ## 78   78        tGravityAcc-correlation()-X,Y
    ## 79   79        tGravityAcc-correlation()-X,Z
    ## 80   80        tGravityAcc-correlation()-Y,Z
    ## 81   81                tBodyAccJerk-mean()-X
    ## 82   82                tBodyAccJerk-mean()-Y
    ## 83   83                tBodyAccJerk-mean()-Z
    ## 84   84                 tBodyAccJerk-std()-X
    ## 85   85                 tBodyAccJerk-std()-Y
    ## 86   86                 tBodyAccJerk-std()-Z
    ## 87   87                 tBodyAccJerk-mad()-X
    ## 88   88                 tBodyAccJerk-mad()-Y
    ## 89   89                 tBodyAccJerk-mad()-Z
    ## 90   90                 tBodyAccJerk-max()-X
    ## 91   91                 tBodyAccJerk-max()-Y
    ## 92   92                 tBodyAccJerk-max()-Z
    ## 93   93                 tBodyAccJerk-min()-X
    ## 94   94                 tBodyAccJerk-min()-Y
    ## 95   95                 tBodyAccJerk-min()-Z
    ## 96   96                   tBodyAccJerk-sma()
    ## 97   97              tBodyAccJerk-energy()-X
    ## 98   98              tBodyAccJerk-energy()-Y
    ## 99   99              tBodyAccJerk-energy()-Z
    ## 100 100                 tBodyAccJerk-iqr()-X
    ## 101 101                 tBodyAccJerk-iqr()-Y
    ## 102 102                 tBodyAccJerk-iqr()-Z
    ## 103 103             tBodyAccJerk-entropy()-X
    ## 104 104             tBodyAccJerk-entropy()-Y
    ## 105 105             tBodyAccJerk-entropy()-Z
    ## 106 106           tBodyAccJerk-arCoeff()-X,1
    ## 107 107           tBodyAccJerk-arCoeff()-X,2
    ## 108 108           tBodyAccJerk-arCoeff()-X,3
    ## 109 109           tBodyAccJerk-arCoeff()-X,4
    ## 110 110           tBodyAccJerk-arCoeff()-Y,1
    ## 111 111           tBodyAccJerk-arCoeff()-Y,2
    ## 112 112           tBodyAccJerk-arCoeff()-Y,3
    ## 113 113           tBodyAccJerk-arCoeff()-Y,4
    ## 114 114           tBodyAccJerk-arCoeff()-Z,1
    ## 115 115           tBodyAccJerk-arCoeff()-Z,2
    ## 116 116           tBodyAccJerk-arCoeff()-Z,3
    ## 117 117           tBodyAccJerk-arCoeff()-Z,4
    ## 118 118       tBodyAccJerk-correlation()-X,Y
    ## 119 119       tBodyAccJerk-correlation()-X,Z
    ## 120 120       tBodyAccJerk-correlation()-Y,Z
    ## 121 121                   tBodyGyro-mean()-X
    ## 122 122                   tBodyGyro-mean()-Y
    ## 123 123                   tBodyGyro-mean()-Z
    ## 124 124                    tBodyGyro-std()-X
    ## 125 125                    tBodyGyro-std()-Y
    ## 126 126                    tBodyGyro-std()-Z
    ## 127 127                    tBodyGyro-mad()-X
    ## 128 128                    tBodyGyro-mad()-Y
    ## 129 129                    tBodyGyro-mad()-Z
    ## 130 130                    tBodyGyro-max()-X
    ## 131 131                    tBodyGyro-max()-Y
    ## 132 132                    tBodyGyro-max()-Z
    ## 133 133                    tBodyGyro-min()-X
    ## 134 134                    tBodyGyro-min()-Y
    ## 135 135                    tBodyGyro-min()-Z
    ## 136 136                      tBodyGyro-sma()
    ## 137 137                 tBodyGyro-energy()-X
    ## 138 138                 tBodyGyro-energy()-Y
    ## 139 139                 tBodyGyro-energy()-Z
    ## 140 140                    tBodyGyro-iqr()-X
    ## 141 141                    tBodyGyro-iqr()-Y
    ## 142 142                    tBodyGyro-iqr()-Z
    ## 143 143                tBodyGyro-entropy()-X
    ## 144 144                tBodyGyro-entropy()-Y
    ## 145 145                tBodyGyro-entropy()-Z
    ## 146 146              tBodyGyro-arCoeff()-X,1
    ## 147 147              tBodyGyro-arCoeff()-X,2
    ## 148 148              tBodyGyro-arCoeff()-X,3
    ## 149 149              tBodyGyro-arCoeff()-X,4
    ## 150 150              tBodyGyro-arCoeff()-Y,1
    ## 151 151              tBodyGyro-arCoeff()-Y,2
    ## 152 152              tBodyGyro-arCoeff()-Y,3
    ## 153 153              tBodyGyro-arCoeff()-Y,4
    ## 154 154              tBodyGyro-arCoeff()-Z,1
    ## 155 155              tBodyGyro-arCoeff()-Z,2
    ## 156 156              tBodyGyro-arCoeff()-Z,3
    ## 157 157              tBodyGyro-arCoeff()-Z,4
    ## 158 158          tBodyGyro-correlation()-X,Y
    ## 159 159          tBodyGyro-correlation()-X,Z
    ## 160 160          tBodyGyro-correlation()-Y,Z
    ## 161 161               tBodyGyroJerk-mean()-X
    ## 162 162               tBodyGyroJerk-mean()-Y
    ## 163 163               tBodyGyroJerk-mean()-Z
    ## 164 164                tBodyGyroJerk-std()-X
    ## 165 165                tBodyGyroJerk-std()-Y
    ## 166 166                tBodyGyroJerk-std()-Z
    ## 167 167                tBodyGyroJerk-mad()-X
    ## 168 168                tBodyGyroJerk-mad()-Y
    ## 169 169                tBodyGyroJerk-mad()-Z
    ## 170 170                tBodyGyroJerk-max()-X
    ## 171 171                tBodyGyroJerk-max()-Y
    ## 172 172                tBodyGyroJerk-max()-Z
    ## 173 173                tBodyGyroJerk-min()-X
    ## 174 174                tBodyGyroJerk-min()-Y
    ## 175 175                tBodyGyroJerk-min()-Z
    ## 176 176                  tBodyGyroJerk-sma()
    ## 177 177             tBodyGyroJerk-energy()-X
    ## 178 178             tBodyGyroJerk-energy()-Y
    ## 179 179             tBodyGyroJerk-energy()-Z
    ## 180 180                tBodyGyroJerk-iqr()-X
    ## 181 181                tBodyGyroJerk-iqr()-Y
    ## 182 182                tBodyGyroJerk-iqr()-Z
    ## 183 183            tBodyGyroJerk-entropy()-X
    ## 184 184            tBodyGyroJerk-entropy()-Y
    ## 185 185            tBodyGyroJerk-entropy()-Z
    ## 186 186          tBodyGyroJerk-arCoeff()-X,1
    ## 187 187          tBodyGyroJerk-arCoeff()-X,2
    ## 188 188          tBodyGyroJerk-arCoeff()-X,3
    ## 189 189          tBodyGyroJerk-arCoeff()-X,4
    ## 190 190          tBodyGyroJerk-arCoeff()-Y,1
    ## 191 191          tBodyGyroJerk-arCoeff()-Y,2
    ## 192 192          tBodyGyroJerk-arCoeff()-Y,3
    ## 193 193          tBodyGyroJerk-arCoeff()-Y,4
    ## 194 194          tBodyGyroJerk-arCoeff()-Z,1
    ## 195 195          tBodyGyroJerk-arCoeff()-Z,2
    ## 196 196          tBodyGyroJerk-arCoeff()-Z,3
    ## 197 197          tBodyGyroJerk-arCoeff()-Z,4
    ## 198 198      tBodyGyroJerk-correlation()-X,Y
    ## 199 199      tBodyGyroJerk-correlation()-X,Z
    ## 200 200      tBodyGyroJerk-correlation()-Y,Z
    ## 201 201                   tBodyAccMag-mean()
    ## 202 202                    tBodyAccMag-std()
    ## 203 203                    tBodyAccMag-mad()
    ## 204 204                    tBodyAccMag-max()
    ## 205 205                    tBodyAccMag-min()
    ## 206 206                    tBodyAccMag-sma()
    ## 207 207                 tBodyAccMag-energy()
    ## 208 208                    tBodyAccMag-iqr()
    ## 209 209                tBodyAccMag-entropy()
    ## 210 210               tBodyAccMag-arCoeff()1
    ## 211 211               tBodyAccMag-arCoeff()2
    ## 212 212               tBodyAccMag-arCoeff()3
    ## 213 213               tBodyAccMag-arCoeff()4
    ## 214 214                tGravityAccMag-mean()
    ## 215 215                 tGravityAccMag-std()
    ## 216 216                 tGravityAccMag-mad()
    ## 217 217                 tGravityAccMag-max()
    ## 218 218                 tGravityAccMag-min()
    ## 219 219                 tGravityAccMag-sma()
    ## 220 220              tGravityAccMag-energy()
    ## 221 221                 tGravityAccMag-iqr()
    ## 222 222             tGravityAccMag-entropy()
    ## 223 223            tGravityAccMag-arCoeff()1
    ## 224 224            tGravityAccMag-arCoeff()2
    ## 225 225            tGravityAccMag-arCoeff()3
    ## 226 226            tGravityAccMag-arCoeff()4
    ## 227 227               tBodyAccJerkMag-mean()
    ## 228 228                tBodyAccJerkMag-std()
    ## 229 229                tBodyAccJerkMag-mad()
    ## 230 230                tBodyAccJerkMag-max()
    ## 231 231                tBodyAccJerkMag-min()
    ## 232 232                tBodyAccJerkMag-sma()
    ## 233 233             tBodyAccJerkMag-energy()
    ## 234 234                tBodyAccJerkMag-iqr()
    ## 235 235            tBodyAccJerkMag-entropy()
    ## 236 236           tBodyAccJerkMag-arCoeff()1
    ## 237 237           tBodyAccJerkMag-arCoeff()2
    ## 238 238           tBodyAccJerkMag-arCoeff()3
    ## 239 239           tBodyAccJerkMag-arCoeff()4
    ## 240 240                  tBodyGyroMag-mean()
    ## 241 241                   tBodyGyroMag-std()
    ## 242 242                   tBodyGyroMag-mad()
    ## 243 243                   tBodyGyroMag-max()
    ## 244 244                   tBodyGyroMag-min()
    ## 245 245                   tBodyGyroMag-sma()
    ## 246 246                tBodyGyroMag-energy()
    ## 247 247                   tBodyGyroMag-iqr()
    ## 248 248               tBodyGyroMag-entropy()
    ## 249 249              tBodyGyroMag-arCoeff()1
    ## 250 250              tBodyGyroMag-arCoeff()2
    ## 251 251              tBodyGyroMag-arCoeff()3
    ## 252 252              tBodyGyroMag-arCoeff()4
    ## 253 253              tBodyGyroJerkMag-mean()
    ## 254 254               tBodyGyroJerkMag-std()
    ## 255 255               tBodyGyroJerkMag-mad()
    ## 256 256               tBodyGyroJerkMag-max()
    ## 257 257               tBodyGyroJerkMag-min()
    ## 258 258               tBodyGyroJerkMag-sma()
    ## 259 259            tBodyGyroJerkMag-energy()
    ## 260 260               tBodyGyroJerkMag-iqr()
    ## 261 261           tBodyGyroJerkMag-entropy()
    ## 262 262          tBodyGyroJerkMag-arCoeff()1
    ## 263 263          tBodyGyroJerkMag-arCoeff()2
    ## 264 264          tBodyGyroJerkMag-arCoeff()3
    ## 265 265          tBodyGyroJerkMag-arCoeff()4
    ## 266 266                    fBodyAcc-mean()-X
    ## 267 267                    fBodyAcc-mean()-Y
    ## 268 268                    fBodyAcc-mean()-Z
    ## 269 269                     fBodyAcc-std()-X
    ## 270 270                     fBodyAcc-std()-Y
    ## 271 271                     fBodyAcc-std()-Z
    ## 272 272                     fBodyAcc-mad()-X
    ## 273 273                     fBodyAcc-mad()-Y
    ## 274 274                     fBodyAcc-mad()-Z
    ## 275 275                     fBodyAcc-max()-X
    ## 276 276                     fBodyAcc-max()-Y
    ## 277 277                     fBodyAcc-max()-Z
    ## 278 278                     fBodyAcc-min()-X
    ## 279 279                     fBodyAcc-min()-Y
    ## 280 280                     fBodyAcc-min()-Z
    ## 281 281                       fBodyAcc-sma()
    ## 282 282                  fBodyAcc-energy()-X
    ## 283 283                  fBodyAcc-energy()-Y
    ## 284 284                  fBodyAcc-energy()-Z
    ## 285 285                     fBodyAcc-iqr()-X
    ## 286 286                     fBodyAcc-iqr()-Y
    ## 287 287                     fBodyAcc-iqr()-Z
    ## 288 288                 fBodyAcc-entropy()-X
    ## 289 289                 fBodyAcc-entropy()-Y
    ## 290 290                 fBodyAcc-entropy()-Z
    ## 291 291                   fBodyAcc-maxInds-X
    ## 292 292                   fBodyAcc-maxInds-Y
    ## 293 293                   fBodyAcc-maxInds-Z
    ## 294 294                fBodyAcc-meanFreq()-X
    ## 295 295                fBodyAcc-meanFreq()-Y
    ## 296 296                fBodyAcc-meanFreq()-Z
    ## 297 297                fBodyAcc-skewness()-X
    ## 298 298                fBodyAcc-kurtosis()-X
    ## 299 299                fBodyAcc-skewness()-Y
    ## 300 300                fBodyAcc-kurtosis()-Y
    ## 301 301                fBodyAcc-skewness()-Z
    ## 302 302                fBodyAcc-kurtosis()-Z
    ## 303 303           fBodyAcc-bandsEnergy()-1,8
    ## 304 304          fBodyAcc-bandsEnergy()-9,16
    ## 305 305         fBodyAcc-bandsEnergy()-17,24
    ## 306 306         fBodyAcc-bandsEnergy()-25,32
    ## 307 307         fBodyAcc-bandsEnergy()-33,40
    ## 308 308         fBodyAcc-bandsEnergy()-41,48
    ## 309 309         fBodyAcc-bandsEnergy()-49,56
    ## 310 310         fBodyAcc-bandsEnergy()-57,64
    ## 311 311          fBodyAcc-bandsEnergy()-1,16
    ## 312 312         fBodyAcc-bandsEnergy()-17,32
    ## 313 313         fBodyAcc-bandsEnergy()-33,48
    ## 314 314         fBodyAcc-bandsEnergy()-49,64
    ## 315 315          fBodyAcc-bandsEnergy()-1,24
    ## 316 316         fBodyAcc-bandsEnergy()-25,48
    ## 317 317           fBodyAcc-bandsEnergy()-1,8
    ## 318 318          fBodyAcc-bandsEnergy()-9,16
    ## 319 319         fBodyAcc-bandsEnergy()-17,24
    ## 320 320         fBodyAcc-bandsEnergy()-25,32
    ## 321 321         fBodyAcc-bandsEnergy()-33,40
    ## 322 322         fBodyAcc-bandsEnergy()-41,48
    ## 323 323         fBodyAcc-bandsEnergy()-49,56
    ## 324 324         fBodyAcc-bandsEnergy()-57,64
    ## 325 325          fBodyAcc-bandsEnergy()-1,16
    ## 326 326         fBodyAcc-bandsEnergy()-17,32
    ## 327 327         fBodyAcc-bandsEnergy()-33,48
    ## 328 328         fBodyAcc-bandsEnergy()-49,64
    ## 329 329          fBodyAcc-bandsEnergy()-1,24
    ## 330 330         fBodyAcc-bandsEnergy()-25,48
    ## 331 331           fBodyAcc-bandsEnergy()-1,8
    ## 332 332          fBodyAcc-bandsEnergy()-9,16
    ## 333 333         fBodyAcc-bandsEnergy()-17,24
    ## 334 334         fBodyAcc-bandsEnergy()-25,32
    ## 335 335         fBodyAcc-bandsEnergy()-33,40
    ## 336 336         fBodyAcc-bandsEnergy()-41,48
    ## 337 337         fBodyAcc-bandsEnergy()-49,56
    ## 338 338         fBodyAcc-bandsEnergy()-57,64
    ## 339 339          fBodyAcc-bandsEnergy()-1,16
    ## 340 340         fBodyAcc-bandsEnergy()-17,32
    ## 341 341         fBodyAcc-bandsEnergy()-33,48
    ## 342 342         fBodyAcc-bandsEnergy()-49,64
    ## 343 343          fBodyAcc-bandsEnergy()-1,24
    ## 344 344         fBodyAcc-bandsEnergy()-25,48
    ## 345 345                fBodyAccJerk-mean()-X
    ## 346 346                fBodyAccJerk-mean()-Y
    ## 347 347                fBodyAccJerk-mean()-Z
    ## 348 348                 fBodyAccJerk-std()-X
    ## 349 349                 fBodyAccJerk-std()-Y
    ## 350 350                 fBodyAccJerk-std()-Z
    ## 351 351                 fBodyAccJerk-mad()-X
    ## 352 352                 fBodyAccJerk-mad()-Y
    ## 353 353                 fBodyAccJerk-mad()-Z
    ## 354 354                 fBodyAccJerk-max()-X
    ## 355 355                 fBodyAccJerk-max()-Y
    ## 356 356                 fBodyAccJerk-max()-Z
    ## 357 357                 fBodyAccJerk-min()-X
    ## 358 358                 fBodyAccJerk-min()-Y
    ## 359 359                 fBodyAccJerk-min()-Z
    ## 360 360                   fBodyAccJerk-sma()
    ## 361 361              fBodyAccJerk-energy()-X
    ## 362 362              fBodyAccJerk-energy()-Y
    ## 363 363              fBodyAccJerk-energy()-Z
    ## 364 364                 fBodyAccJerk-iqr()-X
    ## 365 365                 fBodyAccJerk-iqr()-Y
    ## 366 366                 fBodyAccJerk-iqr()-Z
    ## 367 367             fBodyAccJerk-entropy()-X
    ## 368 368             fBodyAccJerk-entropy()-Y
    ## 369 369             fBodyAccJerk-entropy()-Z
    ## 370 370               fBodyAccJerk-maxInds-X
    ## 371 371               fBodyAccJerk-maxInds-Y
    ## 372 372               fBodyAccJerk-maxInds-Z
    ## 373 373            fBodyAccJerk-meanFreq()-X
    ## 374 374            fBodyAccJerk-meanFreq()-Y
    ## 375 375            fBodyAccJerk-meanFreq()-Z
    ## 376 376            fBodyAccJerk-skewness()-X
    ## 377 377            fBodyAccJerk-kurtosis()-X
    ## 378 378            fBodyAccJerk-skewness()-Y
    ## 379 379            fBodyAccJerk-kurtosis()-Y
    ## 380 380            fBodyAccJerk-skewness()-Z
    ## 381 381            fBodyAccJerk-kurtosis()-Z
    ## 382 382       fBodyAccJerk-bandsEnergy()-1,8
    ## 383 383      fBodyAccJerk-bandsEnergy()-9,16
    ## 384 384     fBodyAccJerk-bandsEnergy()-17,24
    ## 385 385     fBodyAccJerk-bandsEnergy()-25,32
    ## 386 386     fBodyAccJerk-bandsEnergy()-33,40
    ## 387 387     fBodyAccJerk-bandsEnergy()-41,48
    ## 388 388     fBodyAccJerk-bandsEnergy()-49,56
    ## 389 389     fBodyAccJerk-bandsEnergy()-57,64
    ## 390 390      fBodyAccJerk-bandsEnergy()-1,16
    ## 391 391     fBodyAccJerk-bandsEnergy()-17,32
    ## 392 392     fBodyAccJerk-bandsEnergy()-33,48
    ## 393 393     fBodyAccJerk-bandsEnergy()-49,64
    ## 394 394      fBodyAccJerk-bandsEnergy()-1,24
    ## 395 395     fBodyAccJerk-bandsEnergy()-25,48
    ## 396 396       fBodyAccJerk-bandsEnergy()-1,8
    ## 397 397      fBodyAccJerk-bandsEnergy()-9,16
    ## 398 398     fBodyAccJerk-bandsEnergy()-17,24
    ## 399 399     fBodyAccJerk-bandsEnergy()-25,32
    ## 400 400     fBodyAccJerk-bandsEnergy()-33,40
    ## 401 401     fBodyAccJerk-bandsEnergy()-41,48
    ## 402 402     fBodyAccJerk-bandsEnergy()-49,56
    ## 403 403     fBodyAccJerk-bandsEnergy()-57,64
    ## 404 404      fBodyAccJerk-bandsEnergy()-1,16
    ## 405 405     fBodyAccJerk-bandsEnergy()-17,32
    ## 406 406     fBodyAccJerk-bandsEnergy()-33,48
    ## 407 407     fBodyAccJerk-bandsEnergy()-49,64
    ## 408 408      fBodyAccJerk-bandsEnergy()-1,24
    ## 409 409     fBodyAccJerk-bandsEnergy()-25,48
    ## 410 410       fBodyAccJerk-bandsEnergy()-1,8
    ## 411 411      fBodyAccJerk-bandsEnergy()-9,16
    ## 412 412     fBodyAccJerk-bandsEnergy()-17,24
    ## 413 413     fBodyAccJerk-bandsEnergy()-25,32
    ## 414 414     fBodyAccJerk-bandsEnergy()-33,40
    ## 415 415     fBodyAccJerk-bandsEnergy()-41,48
    ## 416 416     fBodyAccJerk-bandsEnergy()-49,56
    ## 417 417     fBodyAccJerk-bandsEnergy()-57,64
    ## 418 418      fBodyAccJerk-bandsEnergy()-1,16
    ## 419 419     fBodyAccJerk-bandsEnergy()-17,32
    ## 420 420     fBodyAccJerk-bandsEnergy()-33,48
    ## 421 421     fBodyAccJerk-bandsEnergy()-49,64
    ## 422 422      fBodyAccJerk-bandsEnergy()-1,24
    ## 423 423     fBodyAccJerk-bandsEnergy()-25,48
    ## 424 424                   fBodyGyro-mean()-X
    ## 425 425                   fBodyGyro-mean()-Y
    ## 426 426                   fBodyGyro-mean()-Z
    ## 427 427                    fBodyGyro-std()-X
    ## 428 428                    fBodyGyro-std()-Y
    ## 429 429                    fBodyGyro-std()-Z
    ## 430 430                    fBodyGyro-mad()-X
    ## 431 431                    fBodyGyro-mad()-Y
    ## 432 432                    fBodyGyro-mad()-Z
    ## 433 433                    fBodyGyro-max()-X
    ## 434 434                    fBodyGyro-max()-Y
    ## 435 435                    fBodyGyro-max()-Z
    ## 436 436                    fBodyGyro-min()-X
    ## 437 437                    fBodyGyro-min()-Y
    ## 438 438                    fBodyGyro-min()-Z
    ## 439 439                      fBodyGyro-sma()
    ## 440 440                 fBodyGyro-energy()-X
    ## 441 441                 fBodyGyro-energy()-Y
    ## 442 442                 fBodyGyro-energy()-Z
    ## 443 443                    fBodyGyro-iqr()-X
    ## 444 444                    fBodyGyro-iqr()-Y
    ## 445 445                    fBodyGyro-iqr()-Z
    ## 446 446                fBodyGyro-entropy()-X
    ## 447 447                fBodyGyro-entropy()-Y
    ## 448 448                fBodyGyro-entropy()-Z
    ## 449 449                  fBodyGyro-maxInds-X
    ## 450 450                  fBodyGyro-maxInds-Y
    ## 451 451                  fBodyGyro-maxInds-Z
    ## 452 452               fBodyGyro-meanFreq()-X
    ## 453 453               fBodyGyro-meanFreq()-Y
    ## 454 454               fBodyGyro-meanFreq()-Z
    ## 455 455               fBodyGyro-skewness()-X
    ## 456 456               fBodyGyro-kurtosis()-X
    ## 457 457               fBodyGyro-skewness()-Y
    ## 458 458               fBodyGyro-kurtosis()-Y
    ## 459 459               fBodyGyro-skewness()-Z
    ## 460 460               fBodyGyro-kurtosis()-Z
    ## 461 461          fBodyGyro-bandsEnergy()-1,8
    ## 462 462         fBodyGyro-bandsEnergy()-9,16
    ## 463 463        fBodyGyro-bandsEnergy()-17,24
    ## 464 464        fBodyGyro-bandsEnergy()-25,32
    ## 465 465        fBodyGyro-bandsEnergy()-33,40
    ## 466 466        fBodyGyro-bandsEnergy()-41,48
    ## 467 467        fBodyGyro-bandsEnergy()-49,56
    ## 468 468        fBodyGyro-bandsEnergy()-57,64
    ## 469 469         fBodyGyro-bandsEnergy()-1,16
    ## 470 470        fBodyGyro-bandsEnergy()-17,32
    ## 471 471        fBodyGyro-bandsEnergy()-33,48
    ## 472 472        fBodyGyro-bandsEnergy()-49,64
    ## 473 473         fBodyGyro-bandsEnergy()-1,24
    ## 474 474        fBodyGyro-bandsEnergy()-25,48
    ## 475 475          fBodyGyro-bandsEnergy()-1,8
    ## 476 476         fBodyGyro-bandsEnergy()-9,16
    ## 477 477        fBodyGyro-bandsEnergy()-17,24
    ## 478 478        fBodyGyro-bandsEnergy()-25,32
    ## 479 479        fBodyGyro-bandsEnergy()-33,40
    ## 480 480        fBodyGyro-bandsEnergy()-41,48
    ## 481 481        fBodyGyro-bandsEnergy()-49,56
    ## 482 482        fBodyGyro-bandsEnergy()-57,64
    ## 483 483         fBodyGyro-bandsEnergy()-1,16
    ## 484 484        fBodyGyro-bandsEnergy()-17,32
    ## 485 485        fBodyGyro-bandsEnergy()-33,48
    ## 486 486        fBodyGyro-bandsEnergy()-49,64
    ## 487 487         fBodyGyro-bandsEnergy()-1,24
    ## 488 488        fBodyGyro-bandsEnergy()-25,48
    ## 489 489          fBodyGyro-bandsEnergy()-1,8
    ## 490 490         fBodyGyro-bandsEnergy()-9,16
    ## 491 491        fBodyGyro-bandsEnergy()-17,24
    ## 492 492        fBodyGyro-bandsEnergy()-25,32
    ## 493 493        fBodyGyro-bandsEnergy()-33,40
    ## 494 494        fBodyGyro-bandsEnergy()-41,48
    ## 495 495        fBodyGyro-bandsEnergy()-49,56
    ## 496 496        fBodyGyro-bandsEnergy()-57,64
    ## 497 497         fBodyGyro-bandsEnergy()-1,16
    ## 498 498        fBodyGyro-bandsEnergy()-17,32
    ## 499 499        fBodyGyro-bandsEnergy()-33,48
    ## 500 500        fBodyGyro-bandsEnergy()-49,64
    ## 501 501         fBodyGyro-bandsEnergy()-1,24
    ## 502 502        fBodyGyro-bandsEnergy()-25,48
    ## 503 503                   fBodyAccMag-mean()
    ## 504 504                    fBodyAccMag-std()
    ## 505 505                    fBodyAccMag-mad()
    ## 506 506                    fBodyAccMag-max()
    ## 507 507                    fBodyAccMag-min()
    ## 508 508                    fBodyAccMag-sma()
    ## 509 509                 fBodyAccMag-energy()
    ## 510 510                    fBodyAccMag-iqr()
    ## 511 511                fBodyAccMag-entropy()
    ## 512 512                  fBodyAccMag-maxInds
    ## 513 513               fBodyAccMag-meanFreq()
    ## 514 514               fBodyAccMag-skewness()
    ## 515 515               fBodyAccMag-kurtosis()
    ## 516 516           fBodyBodyAccJerkMag-mean()
    ## 517 517            fBodyBodyAccJerkMag-std()
    ## 518 518            fBodyBodyAccJerkMag-mad()
    ## 519 519            fBodyBodyAccJerkMag-max()
    ## 520 520            fBodyBodyAccJerkMag-min()
    ## 521 521            fBodyBodyAccJerkMag-sma()
    ## 522 522         fBodyBodyAccJerkMag-energy()
    ## 523 523            fBodyBodyAccJerkMag-iqr()
    ## 524 524        fBodyBodyAccJerkMag-entropy()
    ## 525 525          fBodyBodyAccJerkMag-maxInds
    ## 526 526       fBodyBodyAccJerkMag-meanFreq()
    ## 527 527       fBodyBodyAccJerkMag-skewness()
    ## 528 528       fBodyBodyAccJerkMag-kurtosis()
    ## 529 529              fBodyBodyGyroMag-mean()
    ## 530 530               fBodyBodyGyroMag-std()
    ## 531 531               fBodyBodyGyroMag-mad()
    ## 532 532               fBodyBodyGyroMag-max()
    ## 533 533               fBodyBodyGyroMag-min()
    ## 534 534               fBodyBodyGyroMag-sma()
    ## 535 535            fBodyBodyGyroMag-energy()
    ## 536 536               fBodyBodyGyroMag-iqr()
    ## 537 537           fBodyBodyGyroMag-entropy()
    ## 538 538             fBodyBodyGyroMag-maxInds
    ## 539 539          fBodyBodyGyroMag-meanFreq()
    ## 540 540          fBodyBodyGyroMag-skewness()
    ## 541 541          fBodyBodyGyroMag-kurtosis()
    ## 542 542          fBodyBodyGyroJerkMag-mean()
    ## 543 543           fBodyBodyGyroJerkMag-std()
    ## 544 544           fBodyBodyGyroJerkMag-mad()
    ## 545 545           fBodyBodyGyroJerkMag-max()
    ## 546 546           fBodyBodyGyroJerkMag-min()
    ## 547 547           fBodyBodyGyroJerkMag-sma()
    ## 548 548        fBodyBodyGyroJerkMag-energy()
    ## 549 549           fBodyBodyGyroJerkMag-iqr()
    ## 550 550       fBodyBodyGyroJerkMag-entropy()
    ## 551 551         fBodyBodyGyroJerkMag-maxInds
    ## 552 552      fBodyBodyGyroJerkMag-meanFreq()
    ## 553 553      fBodyBodyGyroJerkMag-skewness()
    ## 554 554      fBodyBodyGyroJerkMag-kurtosis()
    ## 555 555          angle(tBodyAccMean,gravity)
    ## 556 556 angle(tBodyAccJerkMean),gravityMean)
    ## 557 557     angle(tBodyGyroMean,gravityMean)
    ## 558 558 angle(tBodyGyroJerkMean,gravityMean)
    ## 559 559                 angle(X,gravityMean)
    ## 560 560                 angle(Y,gravityMean)
    ## 561 561                 angle(Z,gravityMean)

### 1.3. Original datasets

The original datasets are stored in the following objects :
'subject\_test','x\_test','y\_test','subject\_train','x\_train' and
'y\_train'; which are created by the code contained in the
*"run\_analysis.R"* script:

    ## [1] "RUN: str(subject_test)"

    ## 'data.frame':    2947 obs. of  1 variable:
    ##  $ V1: int  2 2 2 2 2 2 2 2 2 2 ...

    ## [1] "RUN: str(x_test)"

    ## 'data.frame':    2947 obs. of  561 variables:
    ##  $ V1  : num  0.257 0.286 0.275 0.27 0.275 ...
    ##  $ V2  : num  -0.0233 -0.0132 -0.0261 -0.0326 -0.0278 ...
    ##  $ V3  : num  -0.0147 -0.1191 -0.1182 -0.1175 -0.1295 ...
    ##  $ V4  : num  -0.938 -0.975 -0.994 -0.995 -0.994 ...
    ##  $ V5  : num  -0.92 -0.967 -0.97 -0.973 -0.967 ...
    ##  $ V6  : num  -0.668 -0.945 -0.963 -0.967 -0.978 ...
    ##  $ V7  : num  -0.953 -0.987 -0.994 -0.995 -0.994 ...
    ##  $ V8  : num  -0.925 -0.968 -0.971 -0.974 -0.966 ...
    ##  $ V9  : num  -0.674 -0.946 -0.963 -0.969 -0.977 ...
    ##  $ V10 : num  -0.894 -0.894 -0.939 -0.939 -0.939 ...
    ##  $ V11 : num  -0.555 -0.555 -0.569 -0.569 -0.561 ...
    ##  $ V12 : num  -0.466 -0.806 -0.799 -0.799 -0.826 ...
    ##  $ V13 : num  0.717 0.768 0.848 0.848 0.849 ...
    ##  $ V14 : num  0.636 0.684 0.668 0.668 0.671 ...
    ##  $ V15 : num  0.789 0.797 0.822 0.822 0.83 ...
    ##  $ V16 : num  -0.878 -0.969 -0.977 -0.974 -0.975 ...
    ##  $ V17 : num  -0.998 -1 -1 -1 -1 ...
    ##  $ V18 : num  -0.998 -1 -1 -0.999 -0.999 ...
    ##  $ V19 : num  -0.934 -0.998 -0.999 -0.999 -0.999 ...
    ##  $ V20 : num  -0.976 -0.994 -0.993 -0.995 -0.993 ...
    ##  $ V21 : num  -0.95 -0.974 -0.974 -0.979 -0.967 ...
    ##  $ V22 : num  -0.83 -0.951 -0.965 -0.97 -0.976 ...
    ##  $ V23 : num  -0.168 -0.302 -0.618 -0.75 -0.591 ...
    ##  $ V24 : num  -0.379 -0.348 -0.695 -0.899 -0.74 ...
    ##  $ V25 : num  0.246 -0.405 -0.537 -0.554 -0.799 ...
    ##  $ V26 : num  0.521 0.507 0.242 0.175 0.116 ...
    ##  $ V27 : num  -0.4878 -0.1565 -0.115 -0.0513 -0.0289 ...
    ##  $ V28 : num  0.4823 0.0407 0.0327 0.0342 -0.0328 ...
    ##  $ V29 : num  -0.0455 0.273 0.1924 0.1536 0.2943 ...
    ##  $ V30 : num  0.21196 0.19757 -0.01194 0.03077 0.00063 ...
    ##  $ V31 : num  -0.1349 -0.1946 -0.0634 -0.1293 -0.0453 ...
    ##  $ V32 : num  0.131 0.411 0.471 0.446 0.168 ...
    ##  $ V33 : num  -0.0142 -0.3405 -0.5074 -0.4195 -0.0682 ...
    ##  $ V34 : num  -0.106 0.0776 0.1885 0.2715 0.0744 ...
    ##  $ V35 : num  0.0735 -0.084 -0.2316 -0.2258 0.0271 ...
    ##  $ V36 : num  -0.1715 0.0353 0.6321 0.4164 -0.1459 ...
    ##  $ V37 : num  0.0401 -0.0101 -0.5507 -0.2864 -0.0502 ...
    ##  $ V38 : num  0.077 -0.105 0.3057 -0.0638 0.2352 ...
    ##  $ V39 : num  -0.491 -0.429 -0.324 -0.167 0.29 ...
    ##  $ V40 : num  -0.709 0.399 0.28 0.545 0.458 ...
    ##  $ V41 : num  0.936 0.927 0.93 0.929 0.927 ...
    ##  $ V42 : num  -0.283 -0.289 -0.288 -0.293 -0.303 ...
    ##  $ V43 : num  0.115 0.153 0.146 0.143 0.138 ...
    ##  $ V44 : num  -0.925 -0.989 -0.996 -0.993 -0.996 ...
    ##  $ V45 : num  -0.937 -0.984 -0.988 -0.97 -0.971 ...
    ##  $ V46 : num  -0.564 -0.965 -0.982 -0.992 -0.968 ...
    ##  $ V47 : num  -0.93 -0.989 -0.996 -0.993 -0.996 ...
    ##  $ V48 : num  -0.938 -0.983 -0.989 -0.971 -0.971 ...
    ##  $ V49 : num  -0.606 -0.965 -0.98 -0.993 -0.969 ...
    ##  $ V50 : num  0.906 0.856 0.856 0.856 0.854 ...
    ##  $ V51 : num  -0.279 -0.305 -0.305 -0.305 -0.313 ...
    ##  $ V52 : num  0.153 0.153 0.139 0.136 0.134 ...
    ##  $ V53 : num  0.944 0.944 0.949 0.947 0.946 ...
    ##  $ V54 : num  -0.262 -0.262 -0.262 -0.273 -0.279 ...
    ##  $ V55 : num  -0.0762 0.149 0.145 0.1421 0.1309 ...
    ##  $ V56 : num  -0.0178 0.0577 0.0406 0.0461 0.0554 ...
    ##  $ V57 : num  0.829 0.806 0.812 0.809 0.804 ...
    ##  $ V58 : num  -0.865 -0.858 -0.86 -0.854 -0.843 ...
    ##  $ V59 : num  -0.968 -0.957 -0.961 -0.963 -0.965 ...
    ##  $ V60 : num  -0.95 -0.988 -0.996 -0.992 -0.996 ...
    ##  $ V61 : num  -0.946 -0.982 -0.99 -0.973 -0.972 ...
    ##  $ V62 : num  -0.76 -0.971 -0.979 -0.996 -0.969 ...
    ##  $ V63 : num  -0.425 -0.729 -0.823 -0.823 -0.83 ...
    ##  $ V64 : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
    ##  $ V65 : num  0.219 -0.465 -0.53 -0.7 -0.302 ...
    ##  $ V66 : num  -0.43 -0.51 -0.295 -0.343 -0.482 ...
    ##  $ V67 : num  0.431 0.525 0.305 0.359 0.539 ...
    ##  $ V68 : num  -0.432 -0.54 -0.315 -0.375 -0.596 ...
    ##  $ V69 : num  0.433 0.554 0.326 0.392 0.655 ...
    ##  $ V70 : num  -0.795 -0.746 -0.232 -0.233 -0.493 ...
    ##  $ V71 : num  0.781 0.733 0.169 0.176 0.463 ...
    ##  $ V72 : num  -0.78 -0.737 -0.155 -0.169 -0.465 ...
    ##  $ V73 : num  0.785 0.749 0.164 0.185 0.483 ...
    ##  $ V74 : num  -0.984 -0.845 -0.429 -0.297 -0.536 ...
    ##  $ V75 : num  0.987 0.869 0.44 0.304 0.544 ...
    ##  $ V76 : num  -0.989 -0.893 -0.451 -0.311 -0.553 ...
    ##  $ V77 : num  0.988 0.913 0.458 0.315 0.559 ...
    ##  $ V78 : num  0.981 0.945 0.548 0.986 0.998 ...
    ##  $ V79 : num  -0.996 -0.911 -0.335 0.653 0.916 ...
    ##  $ V80 : num  -0.96 -0.739 0.59 0.747 0.929 ...
    ##  $ V81 : num  0.072 0.0702 0.0694 0.0749 0.0784 ...
    ##  $ V82 : num  0.04575 -0.01788 -0.00491 0.03227 0.02228 ...
    ##  $ V83 : num  -0.10604 -0.00172 -0.01367 0.01214 0.00275 ...
    ##  $ V84 : num  -0.907 -0.949 -0.991 -0.991 -0.992 ...
    ##  $ V85 : num  -0.938 -0.973 -0.971 -0.973 -0.979 ...
    ##  $ V86 : num  -0.936 -0.978 -0.973 -0.976 -0.987 ...
    ##  $ V87 : num  -0.916 -0.969 -0.991 -0.99 -0.991 ...
    ##  $ V88 : num  -0.937 -0.974 -0.973 -0.973 -0.977 ...
    ##  $ V89 : num  -0.949 -0.979 -0.975 -0.978 -0.985 ...
    ##  $ V90 : num  -0.903 -0.915 -0.992 -0.992 -0.994 ...
    ##  $ V91 : num  -0.95 -0.981 -0.975 -0.975 -0.986 ...
    ##  $ V92 : num  -0.891 -0.978 -0.962 -0.962 -0.986 ...
    ##  $ V93 : num  0.898 0.898 0.994 0.994 0.994 ...
    ##  $ V94 : num  0.95 0.968 0.976 0.976 0.98 ...
    ##  $ V95 : num  0.946 0.966 0.966 0.97 0.985 ...
    ##  $ V96 : num  -0.931 -0.974 -0.982 -0.983 -0.987 ...
    ##  $ V97 : num  -0.995 -0.998 -1 -1 -1 ...
    ##  $ V98 : num  -0.997 -0.999 -0.999 -0.999 -1 ...
    ##  $ V99 : num  -0.997 -0.999 -0.999 -0.999 -1 ...
    ##   [list output truncated]

    ## [1] "RUN: str(y_test)"

    ## 'data.frame':    2947 obs. of  1 variable:
    ##  $ V1: int  5 5 5 5 5 5 5 5 5 5 ...

    ## [1] "RUN: str(subject_train)"

    ## 'data.frame':    7352 obs. of  1 variable:
    ##  $ V1: int  1 1 1 1 1 1 1 1 1 1 ...

    ## [1] "RUN: str(x_train)"

    ## 'data.frame':    7352 obs. of  561 variables:
    ##  $ V1  : num  0.289 0.278 0.28 0.279 0.277 ...
    ##  $ V2  : num  -0.0203 -0.0164 -0.0195 -0.0262 -0.0166 ...
    ##  $ V3  : num  -0.133 -0.124 -0.113 -0.123 -0.115 ...
    ##  $ V4  : num  -0.995 -0.998 -0.995 -0.996 -0.998 ...
    ##  $ V5  : num  -0.983 -0.975 -0.967 -0.983 -0.981 ...
    ##  $ V6  : num  -0.914 -0.96 -0.979 -0.991 -0.99 ...
    ##  $ V7  : num  -0.995 -0.999 -0.997 -0.997 -0.998 ...
    ##  $ V8  : num  -0.983 -0.975 -0.964 -0.983 -0.98 ...
    ##  $ V9  : num  -0.924 -0.958 -0.977 -0.989 -0.99 ...
    ##  $ V10 : num  -0.935 -0.943 -0.939 -0.939 -0.942 ...
    ##  $ V11 : num  -0.567 -0.558 -0.558 -0.576 -0.569 ...
    ##  $ V12 : num  -0.744 -0.818 -0.818 -0.83 -0.825 ...
    ##  $ V13 : num  0.853 0.849 0.844 0.844 0.849 ...
    ##  $ V14 : num  0.686 0.686 0.682 0.682 0.683 ...
    ##  $ V15 : num  0.814 0.823 0.839 0.838 0.838 ...
    ##  $ V16 : num  -0.966 -0.982 -0.983 -0.986 -0.993 ...
    ##  $ V17 : num  -1 -1 -1 -1 -1 ...
    ##  $ V18 : num  -1 -1 -1 -1 -1 ...
    ##  $ V19 : num  -0.995 -0.998 -0.999 -1 -1 ...
    ##  $ V20 : num  -0.994 -0.999 -0.997 -0.997 -0.998 ...
    ##  $ V21 : num  -0.988 -0.978 -0.965 -0.984 -0.981 ...
    ##  $ V22 : num  -0.943 -0.948 -0.975 -0.986 -0.991 ...
    ##  $ V23 : num  -0.408 -0.715 -0.592 -0.627 -0.787 ...
    ##  $ V24 : num  -0.679 -0.501 -0.486 -0.851 -0.559 ...
    ##  $ V25 : num  -0.602 -0.571 -0.571 -0.912 -0.761 ...
    ##  $ V26 : num  0.9293 0.6116 0.273 0.0614 0.3133 ...
    ##  $ V27 : num  -0.853 -0.3295 -0.0863 0.0748 -0.1312 ...
    ##  $ V28 : num  0.36 0.284 0.337 0.198 0.191 ...
    ##  $ V29 : num  -0.0585 0.2846 -0.1647 -0.2643 0.0869 ...
    ##  $ V30 : num  0.2569 0.1157 0.0172 0.0725 0.2576 ...
    ##  $ V31 : num  -0.2248 -0.091 -0.0745 -0.1553 -0.2725 ...
    ##  $ V32 : num  0.264 0.294 0.342 0.323 0.435 ...
    ##  $ V33 : num  -0.0952 -0.2812 -0.3326 -0.1708 -0.3154 ...
    ##  $ V34 : num  0.279 0.086 0.239 0.295 0.44 ...
    ##  $ V35 : num  -0.4651 -0.0222 -0.1362 -0.3061 -0.2691 ...
    ##  $ V36 : num  0.4919 -0.0167 0.1739 0.4821 0.1794 ...
    ##  $ V37 : num  -0.191 -0.221 -0.299 -0.47 -0.089 ...
    ##  $ V38 : num  0.3763 -0.0134 -0.1247 -0.3057 -0.1558 ...
    ##  $ V39 : num  0.4351 -0.0727 -0.1811 -0.3627 -0.1898 ...
    ##  $ V40 : num  0.661 0.579 0.609 0.507 0.599 ...
    ##  $ V41 : num  0.963 0.967 0.967 0.968 0.968 ...
    ##  $ V42 : num  -0.141 -0.142 -0.142 -0.144 -0.149 ...
    ##  $ V43 : num  0.1154 0.1094 0.1019 0.0999 0.0945 ...
    ##  $ V44 : num  -0.985 -0.997 -1 -0.997 -0.998 ...
    ##  $ V45 : num  -0.982 -0.989 -0.993 -0.981 -0.988 ...
    ##  $ V46 : num  -0.878 -0.932 -0.993 -0.978 -0.979 ...
    ##  $ V47 : num  -0.985 -0.998 -1 -0.996 -0.998 ...
    ##  $ V48 : num  -0.984 -0.99 -0.993 -0.981 -0.989 ...
    ##  $ V49 : num  -0.895 -0.933 -0.993 -0.978 -0.979 ...
    ##  $ V50 : num  0.892 0.892 0.892 0.894 0.894 ...
    ##  $ V51 : num  -0.161 -0.161 -0.164 -0.164 -0.167 ...
    ##  $ V52 : num  0.1247 0.1226 0.0946 0.0934 0.0917 ...
    ##  $ V53 : num  0.977 0.985 0.987 0.987 0.987 ...
    ##  $ V54 : num  -0.123 -0.115 -0.115 -0.121 -0.122 ...
    ##  $ V55 : num  0.0565 0.1028 0.1028 0.0958 0.0941 ...
    ##  $ V56 : num  -0.375 -0.383 -0.402 -0.4 -0.4 ...
    ##  $ V57 : num  0.899 0.908 0.909 0.911 0.912 ...
    ##  $ V58 : num  -0.971 -0.971 -0.97 -0.969 -0.967 ...
    ##  $ V59 : num  -0.976 -0.979 -0.982 -0.982 -0.984 ...
    ##  $ V60 : num  -0.984 -0.999 -1 -0.996 -0.998 ...
    ##  $ V61 : num  -0.989 -0.99 -0.992 -0.981 -0.991 ...
    ##  $ V62 : num  -0.918 -0.942 -0.993 -0.98 -0.98 ...
    ##  $ V63 : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
    ##  $ V64 : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
    ##  $ V65 : num  0.114 -0.21 -0.927 -0.596 -0.617 ...
    ##  $ V66 : num  -0.59042 -0.41006 0.00223 -0.06493 -0.25727 ...
    ##  $ V67 : num  0.5911 0.4139 0.0275 0.0754 0.2689 ...
    ##  $ V68 : num  -0.5918 -0.4176 -0.0567 -0.0858 -0.2807 ...
    ##  $ V69 : num  0.5925 0.4213 0.0855 0.0962 0.2926 ...
    ##  $ V70 : num  -0.745 -0.196 -0.329 -0.295 -0.167 ...
    ##  $ V71 : num  0.7209 0.1253 0.2705 0.2283 0.0899 ...
    ##  $ V72 : num  -0.7124 -0.1056 -0.2545 -0.2063 -0.0663 ...
    ##  $ V73 : num  0.7113 0.1091 0.2576 0.2048 0.0671 ...
    ##  $ V74 : num  -0.995 -0.834 -0.705 -0.385 -0.237 ...
    ##  $ V75 : num  0.996 0.834 0.714 0.386 0.239 ...
    ##  $ V76 : num  -0.996 -0.834 -0.723 -0.387 -0.241 ...
    ##  $ V77 : num  0.992 0.83 0.729 0.385 0.241 ...
    ##  $ V78 : num  0.57 -0.831 -0.181 -0.991 -0.408 ...
    ##  $ V79 : num  0.439 -0.866 0.338 -0.969 -0.185 ...
    ##  $ V80 : num  0.987 0.974 0.643 0.984 0.965 ...
    ##  $ V81 : num  0.078 0.074 0.0736 0.0773 0.0734 ...
    ##  $ V82 : num  0.005 0.00577 0.0031 0.02006 0.01912 ...
    ##  $ V83 : num  -0.06783 0.02938 -0.00905 -0.00986 0.01678 ...
    ##  $ V84 : num  -0.994 -0.996 -0.991 -0.993 -0.996 ...
    ##  $ V85 : num  -0.988 -0.981 -0.981 -0.988 -0.988 ...
    ##  $ V86 : num  -0.994 -0.992 -0.99 -0.993 -0.992 ...
    ##  $ V87 : num  -0.994 -0.996 -0.991 -0.994 -0.997 ...
    ##  $ V88 : num  -0.986 -0.979 -0.979 -0.986 -0.987 ...
    ##  $ V89 : num  -0.993 -0.991 -0.987 -0.991 -0.991 ...
    ##  $ V90 : num  -0.985 -0.995 -0.987 -0.987 -0.997 ...
    ##  $ V91 : num  -0.992 -0.979 -0.979 -0.992 -0.992 ...
    ##  $ V92 : num  -0.993 -0.992 -0.992 -0.99 -0.99 ...
    ##  $ V93 : num  0.99 0.993 0.988 0.988 0.994 ...
    ##  $ V94 : num  0.992 0.992 0.992 0.993 0.993 ...
    ##  $ V95 : num  0.991 0.989 0.989 0.993 0.986 ...
    ##  $ V96 : num  -0.994 -0.991 -0.988 -0.993 -0.994 ...
    ##  $ V97 : num  -1 -1 -1 -1 -1 ...
    ##  $ V98 : num  -1 -1 -1 -1 -1 ...
    ##  $ V99 : num  -1 -1 -1 -1 -1 ...
    ##   [list output truncated]

    ## [1] "RUN: str(y_train)"

    ## 'data.frame':    7352 obs. of  1 variable:
    ##  $ V1: int  5 5 5 5 5 5 5 5 5 5 ...

    ## [1] "RUN: str(activity_names)"

    ## 'data.frame':    6 obs. of  2 variables:
    ##  $ V1: int  1 2 3 4 5 6
    ##  $ V2: Factor w/ 6 levels "LAYING","SITTING",..: 4 6 5 2 3 1

### 1.4. Final notes

The following is the final information included in the *"README.txt"*
file:

**Source: *"README.txt"* file from**
<https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip>

The experiments have been carried out with a group of 30 volunteers
within an age bracket of 19-48 years. Each person performed six
activities (WALKING, WALKING\_UPSTAIRS, WALKING\_DOWNSTAIRS, SITTING,
STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the
waist. Using its embedded accelerometer and gyroscope, we captured
3-axial linear acceleration and 3-axial angular velocity at a constant
rate of 50Hz. The experiments have been video-recorded to label the data
manually. The obtained dataset has been randomly partitioned into two
sets, where 70% of the volunteers was selected for generating the
training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by
applying noise filters and then sampled in fixed-width sliding windows
of 2.56 sec and 50% overlap (128 readings/window). The sensor
acceleration signal, which has gravitational and body motion components,
was separated using a Butterworth low-pass filter into body acceleration
and gravity. The gravitational force is assumed to have only low
frequency components, therefore a filter with 0.3 Hz cutoff frequency
was used. From each window, a vector of features was obtained by
calculating variables from the time and frequency domain. See
'features\_info.txt' for more details.

For each record it is provided:

-   Triaxial acceleration from the accelerometer (total acceleration)
    and the estimated body acceleration.
-   Triaxial Angular velocity from the gyroscope.
-   A 561-feature vector with time and frequency domain variables.
-   Its activity label.
-   An identifier of the subject who carried out the experiment.

Notes:

-   Features are normalized and bounded within \[-1,1\].
-   Each feature vector is a row on the text file.

For more information about this dataset contact:
<activityrecognition@smartlab.ws>

License:

Use of this dataset in publications must be acknowledged by referencing
the following publication \[1\]

\[1\] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and
Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a
Multiclass Hardware-Friendly Support Vector Machine. International
Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz,
Spain. Dec 2012

This dataset is distributed AS-IS and no responsibility implied or
explicit can be addressed to the authors or their institutions for its
use or misuse. Any commercial use is prohibited.

Jorge L. Reyes-Ortiz, Alessandro Ghio, Luca Oneto, Davide Anguita.
November 2012.

2. TIDY DATASET: Merged information with activity and variables labels
----------------------------------------------------------------------

### 2.1. Transformations made to the original dataset

The original datasets are **merged** at a first moment into the 'test'
and 'train' subsets.

The 'test' database results from merging (cbind) the objects mentioned
in section 1.3.: 'subject\_test', 'x\_test' and 'y\_test'

    ## [1] "RUN: str(test)"

    ## 'data.frame':    2947 obs. of  563 variables:
    ##  $ subject                             : int  2 2 2 2 2 2 2 2 2 2 ...
    ##  $ tBodyAcc-mean()-X                   : num  0.257 0.286 0.275 0.27 0.275 ...
    ##  $ tBodyAcc-mean()-Y                   : num  -0.0233 -0.0132 -0.0261 -0.0326 -0.0278 ...
    ##  $ tBodyAcc-mean()-Z                   : num  -0.0147 -0.1191 -0.1182 -0.1175 -0.1295 ...
    ##  $ tBodyAcc-std()-X                    : num  -0.938 -0.975 -0.994 -0.995 -0.994 ...
    ##  $ tBodyAcc-std()-Y                    : num  -0.92 -0.967 -0.97 -0.973 -0.967 ...
    ##  $ tBodyAcc-std()-Z                    : num  -0.668 -0.945 -0.963 -0.967 -0.978 ...
    ##  $ tBodyAcc-mad()-X                    : num  -0.953 -0.987 -0.994 -0.995 -0.994 ...
    ##  $ tBodyAcc-mad()-Y                    : num  -0.925 -0.968 -0.971 -0.974 -0.966 ...
    ##  $ tBodyAcc-mad()-Z                    : num  -0.674 -0.946 -0.963 -0.969 -0.977 ...
    ##  $ tBodyAcc-max()-X                    : num  -0.894 -0.894 -0.939 -0.939 -0.939 ...
    ##  $ tBodyAcc-max()-Y                    : num  -0.555 -0.555 -0.569 -0.569 -0.561 ...
    ##  $ tBodyAcc-max()-Z                    : num  -0.466 -0.806 -0.799 -0.799 -0.826 ...
    ##  $ tBodyAcc-min()-X                    : num  0.717 0.768 0.848 0.848 0.849 ...
    ##  $ tBodyAcc-min()-Y                    : num  0.636 0.684 0.668 0.668 0.671 ...
    ##  $ tBodyAcc-min()-Z                    : num  0.789 0.797 0.822 0.822 0.83 ...
    ##  $ tBodyAcc-sma()                      : num  -0.878 -0.969 -0.977 -0.974 -0.975 ...
    ##  $ tBodyAcc-energy()-X                 : num  -0.998 -1 -1 -1 -1 ...
    ##  $ tBodyAcc-energy()-Y                 : num  -0.998 -1 -1 -0.999 -0.999 ...
    ##  $ tBodyAcc-energy()-Z                 : num  -0.934 -0.998 -0.999 -0.999 -0.999 ...
    ##  $ tBodyAcc-iqr()-X                    : num  -0.976 -0.994 -0.993 -0.995 -0.993 ...
    ##  $ tBodyAcc-iqr()-Y                    : num  -0.95 -0.974 -0.974 -0.979 -0.967 ...
    ##  $ tBodyAcc-iqr()-Z                    : num  -0.83 -0.951 -0.965 -0.97 -0.976 ...
    ##  $ tBodyAcc-entropy()-X                : num  -0.168 -0.302 -0.618 -0.75 -0.591 ...
    ##  $ tBodyAcc-entropy()-Y                : num  -0.379 -0.348 -0.695 -0.899 -0.74 ...
    ##  $ tBodyAcc-entropy()-Z                : num  0.246 -0.405 -0.537 -0.554 -0.799 ...
    ##  $ tBodyAcc-arCoeff()-X,1              : num  0.521 0.507 0.242 0.175 0.116 ...
    ##  $ tBodyAcc-arCoeff()-X,2              : num  -0.4878 -0.1565 -0.115 -0.0513 -0.0289 ...
    ##  $ tBodyAcc-arCoeff()-X,3              : num  0.4823 0.0407 0.0327 0.0342 -0.0328 ...
    ##  $ tBodyAcc-arCoeff()-X,4              : num  -0.0455 0.273 0.1924 0.1536 0.2943 ...
    ##  $ tBodyAcc-arCoeff()-Y,1              : num  0.21196 0.19757 -0.01194 0.03077 0.00063 ...
    ##  $ tBodyAcc-arCoeff()-Y,2              : num  -0.1349 -0.1946 -0.0634 -0.1293 -0.0453 ...
    ##  $ tBodyAcc-arCoeff()-Y,3              : num  0.131 0.411 0.471 0.446 0.168 ...
    ##  $ tBodyAcc-arCoeff()-Y,4              : num  -0.0142 -0.3405 -0.5074 -0.4195 -0.0682 ...
    ##  $ tBodyAcc-arCoeff()-Z,1              : num  -0.106 0.0776 0.1885 0.2715 0.0744 ...
    ##  $ tBodyAcc-arCoeff()-Z,2              : num  0.0735 -0.084 -0.2316 -0.2258 0.0271 ...
    ##  $ tBodyAcc-arCoeff()-Z,3              : num  -0.1715 0.0353 0.6321 0.4164 -0.1459 ...
    ##  $ tBodyAcc-arCoeff()-Z,4              : num  0.0401 -0.0101 -0.5507 -0.2864 -0.0502 ...
    ##  $ tBodyAcc-correlation()-X,Y          : num  0.077 -0.105 0.3057 -0.0638 0.2352 ...
    ##  $ tBodyAcc-correlation()-X,Z          : num  -0.491 -0.429 -0.324 -0.167 0.29 ...
    ##  $ tBodyAcc-correlation()-Y,Z          : num  -0.709 0.399 0.28 0.545 0.458 ...
    ##  $ tGravityAcc-mean()-X                : num  0.936 0.927 0.93 0.929 0.927 ...
    ##  $ tGravityAcc-mean()-Y                : num  -0.283 -0.289 -0.288 -0.293 -0.303 ...
    ##  $ tGravityAcc-mean()-Z                : num  0.115 0.153 0.146 0.143 0.138 ...
    ##  $ tGravityAcc-std()-X                 : num  -0.925 -0.989 -0.996 -0.993 -0.996 ...
    ##  $ tGravityAcc-std()-Y                 : num  -0.937 -0.984 -0.988 -0.97 -0.971 ...
    ##  $ tGravityAcc-std()-Z                 : num  -0.564 -0.965 -0.982 -0.992 -0.968 ...
    ##  $ tGravityAcc-mad()-X                 : num  -0.93 -0.989 -0.996 -0.993 -0.996 ...
    ##  $ tGravityAcc-mad()-Y                 : num  -0.938 -0.983 -0.989 -0.971 -0.971 ...
    ##  $ tGravityAcc-mad()-Z                 : num  -0.606 -0.965 -0.98 -0.993 -0.969 ...
    ##  $ tGravityAcc-max()-X                 : num  0.906 0.856 0.856 0.856 0.854 ...
    ##  $ tGravityAcc-max()-Y                 : num  -0.279 -0.305 -0.305 -0.305 -0.313 ...
    ##  $ tGravityAcc-max()-Z                 : num  0.153 0.153 0.139 0.136 0.134 ...
    ##  $ tGravityAcc-min()-X                 : num  0.944 0.944 0.949 0.947 0.946 ...
    ##  $ tGravityAcc-min()-Y                 : num  -0.262 -0.262 -0.262 -0.273 -0.279 ...
    ##  $ tGravityAcc-min()-Z                 : num  -0.0762 0.149 0.145 0.1421 0.1309 ...
    ##  $ tGravityAcc-sma()                   : num  -0.0178 0.0577 0.0406 0.0461 0.0554 ...
    ##  $ tGravityAcc-energy()-X              : num  0.829 0.806 0.812 0.809 0.804 ...
    ##  $ tGravityAcc-energy()-Y              : num  -0.865 -0.858 -0.86 -0.854 -0.843 ...
    ##  $ tGravityAcc-energy()-Z              : num  -0.968 -0.957 -0.961 -0.963 -0.965 ...
    ##  $ tGravityAcc-iqr()-X                 : num  -0.95 -0.988 -0.996 -0.992 -0.996 ...
    ##  $ tGravityAcc-iqr()-Y                 : num  -0.946 -0.982 -0.99 -0.973 -0.972 ...
    ##  $ tGravityAcc-iqr()-Z                 : num  -0.76 -0.971 -0.979 -0.996 -0.969 ...
    ##  $ tGravityAcc-entropy()-X             : num  -0.425 -0.729 -0.823 -0.823 -0.83 ...
    ##  $ tGravityAcc-entropy()-Y             : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
    ##  $ tGravityAcc-entropy()-Z             : num  0.219 -0.465 -0.53 -0.7 -0.302 ...
    ##  $ tGravityAcc-arCoeff()-X,1           : num  -0.43 -0.51 -0.295 -0.343 -0.482 ...
    ##  $ tGravityAcc-arCoeff()-X,2           : num  0.431 0.525 0.305 0.359 0.539 ...
    ##  $ tGravityAcc-arCoeff()-X,3           : num  -0.432 -0.54 -0.315 -0.375 -0.596 ...
    ##  $ tGravityAcc-arCoeff()-X,4           : num  0.433 0.554 0.326 0.392 0.655 ...
    ##  $ tGravityAcc-arCoeff()-Y,1           : num  -0.795 -0.746 -0.232 -0.233 -0.493 ...
    ##  $ tGravityAcc-arCoeff()-Y,2           : num  0.781 0.733 0.169 0.176 0.463 ...
    ##  $ tGravityAcc-arCoeff()-Y,3           : num  -0.78 -0.737 -0.155 -0.169 -0.465 ...
    ##  $ tGravityAcc-arCoeff()-Y,4           : num  0.785 0.749 0.164 0.185 0.483 ...
    ##  $ tGravityAcc-arCoeff()-Z,1           : num  -0.984 -0.845 -0.429 -0.297 -0.536 ...
    ##  $ tGravityAcc-arCoeff()-Z,2           : num  0.987 0.869 0.44 0.304 0.544 ...
    ##  $ tGravityAcc-arCoeff()-Z,3           : num  -0.989 -0.893 -0.451 -0.311 -0.553 ...
    ##  $ tGravityAcc-arCoeff()-Z,4           : num  0.988 0.913 0.458 0.315 0.559 ...
    ##  $ tGravityAcc-correlation()-X,Y       : num  0.981 0.945 0.548 0.986 0.998 ...
    ##  $ tGravityAcc-correlation()-X,Z       : num  -0.996 -0.911 -0.335 0.653 0.916 ...
    ##  $ tGravityAcc-correlation()-Y,Z       : num  -0.96 -0.739 0.59 0.747 0.929 ...
    ##  $ tBodyAccJerk-mean()-X               : num  0.072 0.0702 0.0694 0.0749 0.0784 ...
    ##  $ tBodyAccJerk-mean()-Y               : num  0.04575 -0.01788 -0.00491 0.03227 0.02228 ...
    ##  $ tBodyAccJerk-mean()-Z               : num  -0.10604 -0.00172 -0.01367 0.01214 0.00275 ...
    ##  $ tBodyAccJerk-std()-X                : num  -0.907 -0.949 -0.991 -0.991 -0.992 ...
    ##  $ tBodyAccJerk-std()-Y                : num  -0.938 -0.973 -0.971 -0.973 -0.979 ...
    ##  $ tBodyAccJerk-std()-Z                : num  -0.936 -0.978 -0.973 -0.976 -0.987 ...
    ##  $ tBodyAccJerk-mad()-X                : num  -0.916 -0.969 -0.991 -0.99 -0.991 ...
    ##  $ tBodyAccJerk-mad()-Y                : num  -0.937 -0.974 -0.973 -0.973 -0.977 ...
    ##  $ tBodyAccJerk-mad()-Z                : num  -0.949 -0.979 -0.975 -0.978 -0.985 ...
    ##  $ tBodyAccJerk-max()-X                : num  -0.903 -0.915 -0.992 -0.992 -0.994 ...
    ##  $ tBodyAccJerk-max()-Y                : num  -0.95 -0.981 -0.975 -0.975 -0.986 ...
    ##  $ tBodyAccJerk-max()-Z                : num  -0.891 -0.978 -0.962 -0.962 -0.986 ...
    ##  $ tBodyAccJerk-min()-X                : num  0.898 0.898 0.994 0.994 0.994 ...
    ##  $ tBodyAccJerk-min()-Y                : num  0.95 0.968 0.976 0.976 0.98 ...
    ##  $ tBodyAccJerk-min()-Z                : num  0.946 0.966 0.966 0.97 0.985 ...
    ##  $ tBodyAccJerk-sma()                  : num  -0.931 -0.974 -0.982 -0.983 -0.987 ...
    ##  $ tBodyAccJerk-energy()-X             : num  -0.995 -0.998 -1 -1 -1 ...
    ##  $ tBodyAccJerk-energy()-Y             : num  -0.997 -0.999 -0.999 -0.999 -1 ...
    ##   [list output truncated]

and it contains 2947 obs. of these 563 variables:

-   A **'subject'** column/variable for which each row identifies the
    subject who performed the activity for the test sample. Its range is
    from 1 to 30.
-   An **'activity\_labels'** column/variable with the activity
    performed by each subject for the test sample. Its range is from 1
    to 6.
-   561 columns/variables, each one corresponding to one
    feature/measurement variable. **These variables are labeled** based
    on the original features list from the **ORIGINAL DATASET**. This
    modification aims to make variable names more descriptive in
    comparison to the original ones.

The 'train' database results from merging (cbind) the objects mentioned
in section 1.3.: 'subject\_train', 'x\_train' and 'y\_train'

    ## [1] "RUN: str(train)"

    ## 'data.frame':    7352 obs. of  563 variables:
    ##  $ subject                             : int  1 1 1 1 1 1 1 1 1 1 ...
    ##  $ tBodyAcc-mean()-X                   : num  0.289 0.278 0.28 0.279 0.277 ...
    ##  $ tBodyAcc-mean()-Y                   : num  -0.0203 -0.0164 -0.0195 -0.0262 -0.0166 ...
    ##  $ tBodyAcc-mean()-Z                   : num  -0.133 -0.124 -0.113 -0.123 -0.115 ...
    ##  $ tBodyAcc-std()-X                    : num  -0.995 -0.998 -0.995 -0.996 -0.998 ...
    ##  $ tBodyAcc-std()-Y                    : num  -0.983 -0.975 -0.967 -0.983 -0.981 ...
    ##  $ tBodyAcc-std()-Z                    : num  -0.914 -0.96 -0.979 -0.991 -0.99 ...
    ##  $ tBodyAcc-mad()-X                    : num  -0.995 -0.999 -0.997 -0.997 -0.998 ...
    ##  $ tBodyAcc-mad()-Y                    : num  -0.983 -0.975 -0.964 -0.983 -0.98 ...
    ##  $ tBodyAcc-mad()-Z                    : num  -0.924 -0.958 -0.977 -0.989 -0.99 ...
    ##  $ tBodyAcc-max()-X                    : num  -0.935 -0.943 -0.939 -0.939 -0.942 ...
    ##  $ tBodyAcc-max()-Y                    : num  -0.567 -0.558 -0.558 -0.576 -0.569 ...
    ##  $ tBodyAcc-max()-Z                    : num  -0.744 -0.818 -0.818 -0.83 -0.825 ...
    ##  $ tBodyAcc-min()-X                    : num  0.853 0.849 0.844 0.844 0.849 ...
    ##  $ tBodyAcc-min()-Y                    : num  0.686 0.686 0.682 0.682 0.683 ...
    ##  $ tBodyAcc-min()-Z                    : num  0.814 0.823 0.839 0.838 0.838 ...
    ##  $ tBodyAcc-sma()                      : num  -0.966 -0.982 -0.983 -0.986 -0.993 ...
    ##  $ tBodyAcc-energy()-X                 : num  -1 -1 -1 -1 -1 ...
    ##  $ tBodyAcc-energy()-Y                 : num  -1 -1 -1 -1 -1 ...
    ##  $ tBodyAcc-energy()-Z                 : num  -0.995 -0.998 -0.999 -1 -1 ...
    ##  $ tBodyAcc-iqr()-X                    : num  -0.994 -0.999 -0.997 -0.997 -0.998 ...
    ##  $ tBodyAcc-iqr()-Y                    : num  -0.988 -0.978 -0.965 -0.984 -0.981 ...
    ##  $ tBodyAcc-iqr()-Z                    : num  -0.943 -0.948 -0.975 -0.986 -0.991 ...
    ##  $ tBodyAcc-entropy()-X                : num  -0.408 -0.715 -0.592 -0.627 -0.787 ...
    ##  $ tBodyAcc-entropy()-Y                : num  -0.679 -0.501 -0.486 -0.851 -0.559 ...
    ##  $ tBodyAcc-entropy()-Z                : num  -0.602 -0.571 -0.571 -0.912 -0.761 ...
    ##  $ tBodyAcc-arCoeff()-X,1              : num  0.9293 0.6116 0.273 0.0614 0.3133 ...
    ##  $ tBodyAcc-arCoeff()-X,2              : num  -0.853 -0.3295 -0.0863 0.0748 -0.1312 ...
    ##  $ tBodyAcc-arCoeff()-X,3              : num  0.36 0.284 0.337 0.198 0.191 ...
    ##  $ tBodyAcc-arCoeff()-X,4              : num  -0.0585 0.2846 -0.1647 -0.2643 0.0869 ...
    ##  $ tBodyAcc-arCoeff()-Y,1              : num  0.2569 0.1157 0.0172 0.0725 0.2576 ...
    ##  $ tBodyAcc-arCoeff()-Y,2              : num  -0.2248 -0.091 -0.0745 -0.1553 -0.2725 ...
    ##  $ tBodyAcc-arCoeff()-Y,3              : num  0.264 0.294 0.342 0.323 0.435 ...
    ##  $ tBodyAcc-arCoeff()-Y,4              : num  -0.0952 -0.2812 -0.3326 -0.1708 -0.3154 ...
    ##  $ tBodyAcc-arCoeff()-Z,1              : num  0.279 0.086 0.239 0.295 0.44 ...
    ##  $ tBodyAcc-arCoeff()-Z,2              : num  -0.4651 -0.0222 -0.1362 -0.3061 -0.2691 ...
    ##  $ tBodyAcc-arCoeff()-Z,3              : num  0.4919 -0.0167 0.1739 0.4821 0.1794 ...
    ##  $ tBodyAcc-arCoeff()-Z,4              : num  -0.191 -0.221 -0.299 -0.47 -0.089 ...
    ##  $ tBodyAcc-correlation()-X,Y          : num  0.3763 -0.0134 -0.1247 -0.3057 -0.1558 ...
    ##  $ tBodyAcc-correlation()-X,Z          : num  0.4351 -0.0727 -0.1811 -0.3627 -0.1898 ...
    ##  $ tBodyAcc-correlation()-Y,Z          : num  0.661 0.579 0.609 0.507 0.599 ...
    ##  $ tGravityAcc-mean()-X                : num  0.963 0.967 0.967 0.968 0.968 ...
    ##  $ tGravityAcc-mean()-Y                : num  -0.141 -0.142 -0.142 -0.144 -0.149 ...
    ##  $ tGravityAcc-mean()-Z                : num  0.1154 0.1094 0.1019 0.0999 0.0945 ...
    ##  $ tGravityAcc-std()-X                 : num  -0.985 -0.997 -1 -0.997 -0.998 ...
    ##  $ tGravityAcc-std()-Y                 : num  -0.982 -0.989 -0.993 -0.981 -0.988 ...
    ##  $ tGravityAcc-std()-Z                 : num  -0.878 -0.932 -0.993 -0.978 -0.979 ...
    ##  $ tGravityAcc-mad()-X                 : num  -0.985 -0.998 -1 -0.996 -0.998 ...
    ##  $ tGravityAcc-mad()-Y                 : num  -0.984 -0.99 -0.993 -0.981 -0.989 ...
    ##  $ tGravityAcc-mad()-Z                 : num  -0.895 -0.933 -0.993 -0.978 -0.979 ...
    ##  $ tGravityAcc-max()-X                 : num  0.892 0.892 0.892 0.894 0.894 ...
    ##  $ tGravityAcc-max()-Y                 : num  -0.161 -0.161 -0.164 -0.164 -0.167 ...
    ##  $ tGravityAcc-max()-Z                 : num  0.1247 0.1226 0.0946 0.0934 0.0917 ...
    ##  $ tGravityAcc-min()-X                 : num  0.977 0.985 0.987 0.987 0.987 ...
    ##  $ tGravityAcc-min()-Y                 : num  -0.123 -0.115 -0.115 -0.121 -0.122 ...
    ##  $ tGravityAcc-min()-Z                 : num  0.0565 0.1028 0.1028 0.0958 0.0941 ...
    ##  $ tGravityAcc-sma()                   : num  -0.375 -0.383 -0.402 -0.4 -0.4 ...
    ##  $ tGravityAcc-energy()-X              : num  0.899 0.908 0.909 0.911 0.912 ...
    ##  $ tGravityAcc-energy()-Y              : num  -0.971 -0.971 -0.97 -0.969 -0.967 ...
    ##  $ tGravityAcc-energy()-Z              : num  -0.976 -0.979 -0.982 -0.982 -0.984 ...
    ##  $ tGravityAcc-iqr()-X                 : num  -0.984 -0.999 -1 -0.996 -0.998 ...
    ##  $ tGravityAcc-iqr()-Y                 : num  -0.989 -0.99 -0.992 -0.981 -0.991 ...
    ##  $ tGravityAcc-iqr()-Z                 : num  -0.918 -0.942 -0.993 -0.98 -0.98 ...
    ##  $ tGravityAcc-entropy()-X             : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
    ##  $ tGravityAcc-entropy()-Y             : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
    ##  $ tGravityAcc-entropy()-Z             : num  0.114 -0.21 -0.927 -0.596 -0.617 ...
    ##  $ tGravityAcc-arCoeff()-X,1           : num  -0.59042 -0.41006 0.00223 -0.06493 -0.25727 ...
    ##  $ tGravityAcc-arCoeff()-X,2           : num  0.5911 0.4139 0.0275 0.0754 0.2689 ...
    ##  $ tGravityAcc-arCoeff()-X,3           : num  -0.5918 -0.4176 -0.0567 -0.0858 -0.2807 ...
    ##  $ tGravityAcc-arCoeff()-X,4           : num  0.5925 0.4213 0.0855 0.0962 0.2926 ...
    ##  $ tGravityAcc-arCoeff()-Y,1           : num  -0.745 -0.196 -0.329 -0.295 -0.167 ...
    ##  $ tGravityAcc-arCoeff()-Y,2           : num  0.7209 0.1253 0.2705 0.2283 0.0899 ...
    ##  $ tGravityAcc-arCoeff()-Y,3           : num  -0.7124 -0.1056 -0.2545 -0.2063 -0.0663 ...
    ##  $ tGravityAcc-arCoeff()-Y,4           : num  0.7113 0.1091 0.2576 0.2048 0.0671 ...
    ##  $ tGravityAcc-arCoeff()-Z,1           : num  -0.995 -0.834 -0.705 -0.385 -0.237 ...
    ##  $ tGravityAcc-arCoeff()-Z,2           : num  0.996 0.834 0.714 0.386 0.239 ...
    ##  $ tGravityAcc-arCoeff()-Z,3           : num  -0.996 -0.834 -0.723 -0.387 -0.241 ...
    ##  $ tGravityAcc-arCoeff()-Z,4           : num  0.992 0.83 0.729 0.385 0.241 ...
    ##  $ tGravityAcc-correlation()-X,Y       : num  0.57 -0.831 -0.181 -0.991 -0.408 ...
    ##  $ tGravityAcc-correlation()-X,Z       : num  0.439 -0.866 0.338 -0.969 -0.185 ...
    ##  $ tGravityAcc-correlation()-Y,Z       : num  0.987 0.974 0.643 0.984 0.965 ...
    ##  $ tBodyAccJerk-mean()-X               : num  0.078 0.074 0.0736 0.0773 0.0734 ...
    ##  $ tBodyAccJerk-mean()-Y               : num  0.005 0.00577 0.0031 0.02006 0.01912 ...
    ##  $ tBodyAccJerk-mean()-Z               : num  -0.06783 0.02938 -0.00905 -0.00986 0.01678 ...
    ##  $ tBodyAccJerk-std()-X                : num  -0.994 -0.996 -0.991 -0.993 -0.996 ...
    ##  $ tBodyAccJerk-std()-Y                : num  -0.988 -0.981 -0.981 -0.988 -0.988 ...
    ##  $ tBodyAccJerk-std()-Z                : num  -0.994 -0.992 -0.99 -0.993 -0.992 ...
    ##  $ tBodyAccJerk-mad()-X                : num  -0.994 -0.996 -0.991 -0.994 -0.997 ...
    ##  $ tBodyAccJerk-mad()-Y                : num  -0.986 -0.979 -0.979 -0.986 -0.987 ...
    ##  $ tBodyAccJerk-mad()-Z                : num  -0.993 -0.991 -0.987 -0.991 -0.991 ...
    ##  $ tBodyAccJerk-max()-X                : num  -0.985 -0.995 -0.987 -0.987 -0.997 ...
    ##  $ tBodyAccJerk-max()-Y                : num  -0.992 -0.979 -0.979 -0.992 -0.992 ...
    ##  $ tBodyAccJerk-max()-Z                : num  -0.993 -0.992 -0.992 -0.99 -0.99 ...
    ##  $ tBodyAccJerk-min()-X                : num  0.99 0.993 0.988 0.988 0.994 ...
    ##  $ tBodyAccJerk-min()-Y                : num  0.992 0.992 0.992 0.993 0.993 ...
    ##  $ tBodyAccJerk-min()-Z                : num  0.991 0.989 0.989 0.993 0.986 ...
    ##  $ tBodyAccJerk-sma()                  : num  -0.994 -0.991 -0.988 -0.993 -0.994 ...
    ##  $ tBodyAccJerk-energy()-X             : num  -1 -1 -1 -1 -1 ...
    ##  $ tBodyAccJerk-energy()-Y             : num  -1 -1 -1 -1 -1 ...
    ##   [list output truncated]

and it contains 7352 obs. of these 563 variables:

-   A **'subject'** column/variable for which each row identifies the
    subject who performed the activity for the test sample. Its range is
    from 1 to 30.
-   An **'activity\_labels'** column/variable with the activity
    performed by each subject for the test sample. Its range is from 1
    to 6.
-   561 columns/variables, each one corresponding to one
    feature/measurement variable. **These variables are labeled** based
    on the original features list from the **ORIGINAL DATASET**. This
    modification aims to make variable names more descriptive in
    comparison to the original ones.

Finally, the **'complete\_data'** object merges (rbind) 'test' and
'train' sample sets into one complete data set containing in total 10299
obs. of 563 variables.

    ## [1] "RUN: str(complete_data)"

    ## 'data.frame':    10299 obs. of  563 variables:
    ##  $ subject                             : int  1 1 1 1 1 1 1 1 1 1 ...
    ##  $ tBodyAcc-mean()-X                   : num  0.289 0.278 0.28 0.279 0.277 ...
    ##  $ tBodyAcc-mean()-Y                   : num  -0.0203 -0.0164 -0.0195 -0.0262 -0.0166 ...
    ##  $ tBodyAcc-mean()-Z                   : num  -0.133 -0.124 -0.113 -0.123 -0.115 ...
    ##  $ tBodyAcc-std()-X                    : num  -0.995 -0.998 -0.995 -0.996 -0.998 ...
    ##  $ tBodyAcc-std()-Y                    : num  -0.983 -0.975 -0.967 -0.983 -0.981 ...
    ##  $ tBodyAcc-std()-Z                    : num  -0.914 -0.96 -0.979 -0.991 -0.99 ...
    ##  $ tBodyAcc-mad()-X                    : num  -0.995 -0.999 -0.997 -0.997 -0.998 ...
    ##  $ tBodyAcc-mad()-Y                    : num  -0.983 -0.975 -0.964 -0.983 -0.98 ...
    ##  $ tBodyAcc-mad()-Z                    : num  -0.924 -0.958 -0.977 -0.989 -0.99 ...
    ##  $ tBodyAcc-max()-X                    : num  -0.935 -0.943 -0.939 -0.939 -0.942 ...
    ##  $ tBodyAcc-max()-Y                    : num  -0.567 -0.558 -0.558 -0.576 -0.569 ...
    ##  $ tBodyAcc-max()-Z                    : num  -0.744 -0.818 -0.818 -0.83 -0.825 ...
    ##  $ tBodyAcc-min()-X                    : num  0.853 0.849 0.844 0.844 0.849 ...
    ##  $ tBodyAcc-min()-Y                    : num  0.686 0.686 0.682 0.682 0.683 ...
    ##  $ tBodyAcc-min()-Z                    : num  0.814 0.823 0.839 0.838 0.838 ...
    ##  $ tBodyAcc-sma()                      : num  -0.966 -0.982 -0.983 -0.986 -0.993 ...
    ##  $ tBodyAcc-energy()-X                 : num  -1 -1 -1 -1 -1 ...
    ##  $ tBodyAcc-energy()-Y                 : num  -1 -1 -1 -1 -1 ...
    ##  $ tBodyAcc-energy()-Z                 : num  -0.995 -0.998 -0.999 -1 -1 ...
    ##  $ tBodyAcc-iqr()-X                    : num  -0.994 -0.999 -0.997 -0.997 -0.998 ...
    ##  $ tBodyAcc-iqr()-Y                    : num  -0.988 -0.978 -0.965 -0.984 -0.981 ...
    ##  $ tBodyAcc-iqr()-Z                    : num  -0.943 -0.948 -0.975 -0.986 -0.991 ...
    ##  $ tBodyAcc-entropy()-X                : num  -0.408 -0.715 -0.592 -0.627 -0.787 ...
    ##  $ tBodyAcc-entropy()-Y                : num  -0.679 -0.501 -0.486 -0.851 -0.559 ...
    ##  $ tBodyAcc-entropy()-Z                : num  -0.602 -0.571 -0.571 -0.912 -0.761 ...
    ##  $ tBodyAcc-arCoeff()-X,1              : num  0.9293 0.6116 0.273 0.0614 0.3133 ...
    ##  $ tBodyAcc-arCoeff()-X,2              : num  -0.853 -0.3295 -0.0863 0.0748 -0.1312 ...
    ##  $ tBodyAcc-arCoeff()-X,3              : num  0.36 0.284 0.337 0.198 0.191 ...
    ##  $ tBodyAcc-arCoeff()-X,4              : num  -0.0585 0.2846 -0.1647 -0.2643 0.0869 ...
    ##  $ tBodyAcc-arCoeff()-Y,1              : num  0.2569 0.1157 0.0172 0.0725 0.2576 ...
    ##  $ tBodyAcc-arCoeff()-Y,2              : num  -0.2248 -0.091 -0.0745 -0.1553 -0.2725 ...
    ##  $ tBodyAcc-arCoeff()-Y,3              : num  0.264 0.294 0.342 0.323 0.435 ...
    ##  $ tBodyAcc-arCoeff()-Y,4              : num  -0.0952 -0.2812 -0.3326 -0.1708 -0.3154 ...
    ##  $ tBodyAcc-arCoeff()-Z,1              : num  0.279 0.086 0.239 0.295 0.44 ...
    ##  $ tBodyAcc-arCoeff()-Z,2              : num  -0.4651 -0.0222 -0.1362 -0.3061 -0.2691 ...
    ##  $ tBodyAcc-arCoeff()-Z,3              : num  0.4919 -0.0167 0.1739 0.4821 0.1794 ...
    ##  $ tBodyAcc-arCoeff()-Z,4              : num  -0.191 -0.221 -0.299 -0.47 -0.089 ...
    ##  $ tBodyAcc-correlation()-X,Y          : num  0.3763 -0.0134 -0.1247 -0.3057 -0.1558 ...
    ##  $ tBodyAcc-correlation()-X,Z          : num  0.4351 -0.0727 -0.1811 -0.3627 -0.1898 ...
    ##  $ tBodyAcc-correlation()-Y,Z          : num  0.661 0.579 0.609 0.507 0.599 ...
    ##  $ tGravityAcc-mean()-X                : num  0.963 0.967 0.967 0.968 0.968 ...
    ##  $ tGravityAcc-mean()-Y                : num  -0.141 -0.142 -0.142 -0.144 -0.149 ...
    ##  $ tGravityAcc-mean()-Z                : num  0.1154 0.1094 0.1019 0.0999 0.0945 ...
    ##  $ tGravityAcc-std()-X                 : num  -0.985 -0.997 -1 -0.997 -0.998 ...
    ##  $ tGravityAcc-std()-Y                 : num  -0.982 -0.989 -0.993 -0.981 -0.988 ...
    ##  $ tGravityAcc-std()-Z                 : num  -0.878 -0.932 -0.993 -0.978 -0.979 ...
    ##  $ tGravityAcc-mad()-X                 : num  -0.985 -0.998 -1 -0.996 -0.998 ...
    ##  $ tGravityAcc-mad()-Y                 : num  -0.984 -0.99 -0.993 -0.981 -0.989 ...
    ##  $ tGravityAcc-mad()-Z                 : num  -0.895 -0.933 -0.993 -0.978 -0.979 ...
    ##  $ tGravityAcc-max()-X                 : num  0.892 0.892 0.892 0.894 0.894 ...
    ##  $ tGravityAcc-max()-Y                 : num  -0.161 -0.161 -0.164 -0.164 -0.167 ...
    ##  $ tGravityAcc-max()-Z                 : num  0.1247 0.1226 0.0946 0.0934 0.0917 ...
    ##  $ tGravityAcc-min()-X                 : num  0.977 0.985 0.987 0.987 0.987 ...
    ##  $ tGravityAcc-min()-Y                 : num  -0.123 -0.115 -0.115 -0.121 -0.122 ...
    ##  $ tGravityAcc-min()-Z                 : num  0.0565 0.1028 0.1028 0.0958 0.0941 ...
    ##  $ tGravityAcc-sma()                   : num  -0.375 -0.383 -0.402 -0.4 -0.4 ...
    ##  $ tGravityAcc-energy()-X              : num  0.899 0.908 0.909 0.911 0.912 ...
    ##  $ tGravityAcc-energy()-Y              : num  -0.971 -0.971 -0.97 -0.969 -0.967 ...
    ##  $ tGravityAcc-energy()-Z              : num  -0.976 -0.979 -0.982 -0.982 -0.984 ...
    ##  $ tGravityAcc-iqr()-X                 : num  -0.984 -0.999 -1 -0.996 -0.998 ...
    ##  $ tGravityAcc-iqr()-Y                 : num  -0.989 -0.99 -0.992 -0.981 -0.991 ...
    ##  $ tGravityAcc-iqr()-Z                 : num  -0.918 -0.942 -0.993 -0.98 -0.98 ...
    ##  $ tGravityAcc-entropy()-X             : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
    ##  $ tGravityAcc-entropy()-Y             : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
    ##  $ tGravityAcc-entropy()-Z             : num  0.114 -0.21 -0.927 -0.596 -0.617 ...
    ##  $ tGravityAcc-arCoeff()-X,1           : num  -0.59042 -0.41006 0.00223 -0.06493 -0.25727 ...
    ##  $ tGravityAcc-arCoeff()-X,2           : num  0.5911 0.4139 0.0275 0.0754 0.2689 ...
    ##  $ tGravityAcc-arCoeff()-X,3           : num  -0.5918 -0.4176 -0.0567 -0.0858 -0.2807 ...
    ##  $ tGravityAcc-arCoeff()-X,4           : num  0.5925 0.4213 0.0855 0.0962 0.2926 ...
    ##  $ tGravityAcc-arCoeff()-Y,1           : num  -0.745 -0.196 -0.329 -0.295 -0.167 ...
    ##  $ tGravityAcc-arCoeff()-Y,2           : num  0.7209 0.1253 0.2705 0.2283 0.0899 ...
    ##  $ tGravityAcc-arCoeff()-Y,3           : num  -0.7124 -0.1056 -0.2545 -0.2063 -0.0663 ...
    ##  $ tGravityAcc-arCoeff()-Y,4           : num  0.7113 0.1091 0.2576 0.2048 0.0671 ...
    ##  $ tGravityAcc-arCoeff()-Z,1           : num  -0.995 -0.834 -0.705 -0.385 -0.237 ...
    ##  $ tGravityAcc-arCoeff()-Z,2           : num  0.996 0.834 0.714 0.386 0.239 ...
    ##  $ tGravityAcc-arCoeff()-Z,3           : num  -0.996 -0.834 -0.723 -0.387 -0.241 ...
    ##  $ tGravityAcc-arCoeff()-Z,4           : num  0.992 0.83 0.729 0.385 0.241 ...
    ##  $ tGravityAcc-correlation()-X,Y       : num  0.57 -0.831 -0.181 -0.991 -0.408 ...
    ##  $ tGravityAcc-correlation()-X,Z       : num  0.439 -0.866 0.338 -0.969 -0.185 ...
    ##  $ tGravityAcc-correlation()-Y,Z       : num  0.987 0.974 0.643 0.984 0.965 ...
    ##  $ tBodyAccJerk-mean()-X               : num  0.078 0.074 0.0736 0.0773 0.0734 ...
    ##  $ tBodyAccJerk-mean()-Y               : num  0.005 0.00577 0.0031 0.02006 0.01912 ...
    ##  $ tBodyAccJerk-mean()-Z               : num  -0.06783 0.02938 -0.00905 -0.00986 0.01678 ...
    ##  $ tBodyAccJerk-std()-X                : num  -0.994 -0.996 -0.991 -0.993 -0.996 ...
    ##  $ tBodyAccJerk-std()-Y                : num  -0.988 -0.981 -0.981 -0.988 -0.988 ...
    ##  $ tBodyAccJerk-std()-Z                : num  -0.994 -0.992 -0.99 -0.993 -0.992 ...
    ##  $ tBodyAccJerk-mad()-X                : num  -0.994 -0.996 -0.991 -0.994 -0.997 ...
    ##  $ tBodyAccJerk-mad()-Y                : num  -0.986 -0.979 -0.979 -0.986 -0.987 ...
    ##  $ tBodyAccJerk-mad()-Z                : num  -0.993 -0.991 -0.987 -0.991 -0.991 ...
    ##  $ tBodyAccJerk-max()-X                : num  -0.985 -0.995 -0.987 -0.987 -0.997 ...
    ##  $ tBodyAccJerk-max()-Y                : num  -0.992 -0.979 -0.979 -0.992 -0.992 ...
    ##  $ tBodyAccJerk-max()-Z                : num  -0.993 -0.992 -0.992 -0.99 -0.99 ...
    ##  $ tBodyAccJerk-min()-X                : num  0.99 0.993 0.988 0.988 0.994 ...
    ##  $ tBodyAccJerk-min()-Y                : num  0.992 0.992 0.992 0.993 0.993 ...
    ##  $ tBodyAccJerk-min()-Z                : num  0.991 0.989 0.989 0.993 0.986 ...
    ##  $ tBodyAccJerk-sma()                  : num  -0.994 -0.991 -0.988 -0.993 -0.994 ...
    ##  $ tBodyAccJerk-energy()-X             : num  -1 -1 -1 -1 -1 ...
    ##  $ tBodyAccJerk-energy()-Y             : num  -1 -1 -1 -1 -1 ...
    ##   [list output truncated]

Once the **'complete\_data'** database is obtained, those **variables
that estimate mean values or standard deviation values are preserved**,
while the rest of the measurement variables are eliminated. This
transformation aims to facilitate the manipulation of the data that it
is important to the analysis. In order to do this, variables
labels/names are evaluated to identify those that contain the words
'mean()' or 'std()' on it. The new dataset is stored in an object called
**'tidy\_data**

After this, the **'activity\_labels' variable is tranformed** into a new
variable named **'activity'**. This transformation consists on replacing
each number representing an activity, by the activity name itself in
order to make the variable content more descriptive. In order to do
this, it is used the classification given in the file
**"activity\_labels.txt"**

**Source: *"activity\_labels.txt"* file from**
<https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip>

where V1 refers to the level (1 to 6), and V2 refers to the activity
that correspond to each level:

    ## [1] "RUN: activity_names"

    ##   V1                 V2
    ## 1  1            WALKING
    ## 2  2   WALKING_UPSTAIRS
    ## 3  3 WALKING_DOWNSTAIRS
    ## 4  4            SITTING
    ## 5  5           STANDING
    ## 6  6             LAYING

The 'activity\_labels' variable is then removed, while the new
**'activity'** variable is tranformed into a **factor**. On the other
hand, the **'subject'** variable is set to be a **factor** even though
there is no hierarchy.

From the merging process, variables were labeled. Further information
can be found in section 2.2. The final dataset is stored in the object
called **'tidy\_data'**.

### 2.2. Variables

The labeling provided in the feature vector from the file
*"features.txt"*

**Source: *"features.txt"* file from**
<https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip>

is used in order to label the dataset **measurement variables (columns 2
to 67)**. This labeling provides appropiate descriptive names for each
measurement variable, and for this reason it is not modified. In other
words, these variable names are found to be sufficiently descriptive and
to bring comprenhensive information about each measurement variable.
Specifically,each component of the name provides specific and accurate
information:

-   1st component: a letter indicates the variable domain (t sets for
    time and f sets for frequency).
-   2nd component: gives information about the motion components (Body
    sets for body motion and Gravity sets for gravitational motion).
-   3rd component: tells whether the sensor signals were captured by the
    accelerometer or by the gyroscope (Acc sets for accelerometer and
    Gyro sets for Gyroscope).
-   4th component (present just in some cases): tells whether Jerk
    signals or magnitude were calculated (Jerk sets for Jerk signals and
    Mag sets for magnitude).
-   5th component: gives information about the set of variables that
    were estimated from the signals captured (mean() sets for mean value
    and std() sets for standard deviation).
-   6th component (present just in some cases): tells the direction of
    the signal captured (X sets for x-axis direction, Y sets for y-axis
    direction and Z sets for z-axis direction)

The variable that identifies the **subject who performed the activity
(column 1)** was labeled as "subject" which is considered to be a
sufficiently descriptive name for this variable in particular.

The variable that identifies the **activity performed by each subject
(column 68)** was labeled as "activity" which is considered to be a
sufficiently descriptive name for this variable in particular.

These are the final **variables of the TIDY DATASET** stored in the
**'tidy\_data'** object:

    ## [1] "RUN: names(tidy_data)"

    ##  [1] "subject"                     "tBodyAcc-mean()-X"          
    ##  [3] "tBodyAcc-mean()-Y"           "tBodyAcc-mean()-Z"          
    ##  [5] "tGravityAcc-mean()-X"        "tGravityAcc-mean()-Y"       
    ##  [7] "tGravityAcc-mean()-Z"        "tBodyAccJerk-mean()-X"      
    ##  [9] "tBodyAccJerk-mean()-Y"       "tBodyAccJerk-mean()-Z"      
    ## [11] "tBodyGyro-mean()-X"          "tBodyGyro-mean()-Y"         
    ## [13] "tBodyGyro-mean()-Z"          "tBodyGyroJerk-mean()-X"     
    ## [15] "tBodyGyroJerk-mean()-Y"      "tBodyGyroJerk-mean()-Z"     
    ## [17] "tBodyAccMag-mean()"          "tGravityAccMag-mean()"      
    ## [19] "tBodyAccJerkMag-mean()"      "tBodyGyroMag-mean()"        
    ## [21] "tBodyGyroJerkMag-mean()"     "fBodyAcc-mean()-X"          
    ## [23] "fBodyAcc-mean()-Y"           "fBodyAcc-mean()-Z"          
    ## [25] "fBodyAccJerk-mean()-X"       "fBodyAccJerk-mean()-Y"      
    ## [27] "fBodyAccJerk-mean()-Z"       "fBodyGyro-mean()-X"         
    ## [29] "fBodyGyro-mean()-Y"          "fBodyGyro-mean()-Z"         
    ## [31] "fBodyAccMag-mean()"          "fBodyBodyAccJerkMag-mean()" 
    ## [33] "fBodyBodyGyroMag-mean()"     "fBodyBodyGyroJerkMag-mean()"
    ## [35] "tBodyAcc-std()-X"            "tBodyAcc-std()-Y"           
    ## [37] "tBodyAcc-std()-Z"            "tGravityAcc-std()-X"        
    ## [39] "tGravityAcc-std()-Y"         "tGravityAcc-std()-Z"        
    ## [41] "tBodyAccJerk-std()-X"        "tBodyAccJerk-std()-Y"       
    ## [43] "tBodyAccJerk-std()-Z"        "tBodyGyro-std()-X"          
    ## [45] "tBodyGyro-std()-Y"           "tBodyGyro-std()-Z"          
    ## [47] "tBodyGyroJerk-std()-X"       "tBodyGyroJerk-std()-Y"      
    ## [49] "tBodyGyroJerk-std()-Z"       "tBodyAccMag-std()"          
    ## [51] "tGravityAccMag-std()"        "tBodyAccJerkMag-std()"      
    ## [53] "tBodyGyroMag-std()"          "tBodyGyroJerkMag-std()"     
    ## [55] "fBodyAcc-std()-X"            "fBodyAcc-std()-Y"           
    ## [57] "fBodyAcc-std()-Z"            "fBodyAccJerk-std()-X"       
    ## [59] "fBodyAccJerk-std()-Y"        "fBodyAccJerk-std()-Z"       
    ## [61] "fBodyGyro-std()-X"           "fBodyGyro-std()-Y"          
    ## [63] "fBodyGyro-std()-Z"           "fBodyAccMag-std()"          
    ## [65] "fBodyBodyAccJerkMag-std()"   "fBodyBodyGyroMag-std()"     
    ## [67] "fBodyBodyGyroJerkMag-std()"  "activity"

### 2.3. Units

'subject' is a factor variable that identifies the subject who perfomed
the activity. The ID number ranges from 1 to 30.

    ## [1] "RUN: str(tidy_data$subject)"

    ##  Factor w/ 30 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...

'activity' is a factor variable that identifies the activity performed
by each subject. It has 6 levels, 1 for each posible activity:

    ## [1] "RUN: str(tidy_data$activity)"

    ##  Factor w/ 6 levels "LAYING","SITTING",..: 3 3 3 3 3 3 3 3 3 3 ...

    ## [1] "RUN: levels(tidy_data$activity)"

    ## [1] "LAYING"             "SITTING"            "STANDING"          
    ## [4] "WALKING"            "WALKING_DOWNSTAIRS" "WALKING_UPSTAIRS"

The original units domain of the measurements variables were time (t-)
**s** and frequency (f-) **Hz**. Nevertheless, since the **data was
normalized** and bounded within \[-1,1\] from the **ORIGINAL DATASET**,
the units of measurement were eliminated at a first moment enabling
easily future comparation. In this way, all the measurement variables
are numeric:

    ## [1] "RUN: str(tidy_data[2:67])"

    ## 'data.frame':    10299 obs. of  66 variables:
    ##  $ tBodyAcc-mean()-X          : num  0.289 0.278 0.28 0.279 0.277 ...
    ##  $ tBodyAcc-mean()-Y          : num  -0.0203 -0.0164 -0.0195 -0.0262 -0.0166 ...
    ##  $ tBodyAcc-mean()-Z          : num  -0.133 -0.124 -0.113 -0.123 -0.115 ...
    ##  $ tGravityAcc-mean()-X       : num  0.963 0.967 0.967 0.968 0.968 ...
    ##  $ tGravityAcc-mean()-Y       : num  -0.141 -0.142 -0.142 -0.144 -0.149 ...
    ##  $ tGravityAcc-mean()-Z       : num  0.1154 0.1094 0.1019 0.0999 0.0945 ...
    ##  $ tBodyAccJerk-mean()-X      : num  0.078 0.074 0.0736 0.0773 0.0734 ...
    ##  $ tBodyAccJerk-mean()-Y      : num  0.005 0.00577 0.0031 0.02006 0.01912 ...
    ##  $ tBodyAccJerk-mean()-Z      : num  -0.06783 0.02938 -0.00905 -0.00986 0.01678 ...
    ##  $ tBodyGyro-mean()-X         : num  -0.0061 -0.0161 -0.0317 -0.0434 -0.034 ...
    ##  $ tBodyGyro-mean()-Y         : num  -0.0314 -0.0839 -0.1023 -0.0914 -0.0747 ...
    ##  $ tBodyGyro-mean()-Z         : num  0.1077 0.1006 0.0961 0.0855 0.0774 ...
    ##  $ tBodyGyroJerk-mean()-X     : num  -0.0992 -0.1105 -0.1085 -0.0912 -0.0908 ...
    ##  $ tBodyGyroJerk-mean()-Y     : num  -0.0555 -0.0448 -0.0424 -0.0363 -0.0376 ...
    ##  $ tBodyGyroJerk-mean()-Z     : num  -0.062 -0.0592 -0.0558 -0.0605 -0.0583 ...
    ##  $ tBodyAccMag-mean()         : num  -0.959 -0.979 -0.984 -0.987 -0.993 ...
    ##  $ tGravityAccMag-mean()      : num  -0.959 -0.979 -0.984 -0.987 -0.993 ...
    ##  $ tBodyAccJerkMag-mean()     : num  -0.993 -0.991 -0.989 -0.993 -0.993 ...
    ##  $ tBodyGyroMag-mean()        : num  -0.969 -0.981 -0.976 -0.982 -0.985 ...
    ##  $ tBodyGyroJerkMag-mean()    : num  -0.994 -0.995 -0.993 -0.996 -0.996 ...
    ##  $ fBodyAcc-mean()-X          : num  -0.995 -0.997 -0.994 -0.995 -0.997 ...
    ##  $ fBodyAcc-mean()-Y          : num  -0.983 -0.977 -0.973 -0.984 -0.982 ...
    ##  $ fBodyAcc-mean()-Z          : num  -0.939 -0.974 -0.983 -0.991 -0.988 ...
    ##  $ fBodyAccJerk-mean()-X      : num  -0.992 -0.995 -0.991 -0.994 -0.996 ...
    ##  $ fBodyAccJerk-mean()-Y      : num  -0.987 -0.981 -0.982 -0.989 -0.989 ...
    ##  $ fBodyAccJerk-mean()-Z      : num  -0.99 -0.99 -0.988 -0.991 -0.991 ...
    ##  $ fBodyGyro-mean()-X         : num  -0.987 -0.977 -0.975 -0.987 -0.982 ...
    ##  $ fBodyGyro-mean()-Y         : num  -0.982 -0.993 -0.994 -0.994 -0.993 ...
    ##  $ fBodyGyro-mean()-Z         : num  -0.99 -0.99 -0.987 -0.987 -0.989 ...
    ##  $ fBodyAccMag-mean()         : num  -0.952 -0.981 -0.988 -0.988 -0.994 ...
    ##  $ fBodyBodyAccJerkMag-mean() : num  -0.994 -0.99 -0.989 -0.993 -0.996 ...
    ##  $ fBodyBodyGyroMag-mean()    : num  -0.98 -0.988 -0.989 -0.989 -0.991 ...
    ##  $ fBodyBodyGyroJerkMag-mean(): num  -0.992 -0.996 -0.995 -0.995 -0.995 ...
    ##  $ tBodyAcc-std()-X           : num  -0.995 -0.998 -0.995 -0.996 -0.998 ...
    ##  $ tBodyAcc-std()-Y           : num  -0.983 -0.975 -0.967 -0.983 -0.981 ...
    ##  $ tBodyAcc-std()-Z           : num  -0.914 -0.96 -0.979 -0.991 -0.99 ...
    ##  $ tGravityAcc-std()-X        : num  -0.985 -0.997 -1 -0.997 -0.998 ...
    ##  $ tGravityAcc-std()-Y        : num  -0.982 -0.989 -0.993 -0.981 -0.988 ...
    ##  $ tGravityAcc-std()-Z        : num  -0.878 -0.932 -0.993 -0.978 -0.979 ...
    ##  $ tBodyAccJerk-std()-X       : num  -0.994 -0.996 -0.991 -0.993 -0.996 ...
    ##  $ tBodyAccJerk-std()-Y       : num  -0.988 -0.981 -0.981 -0.988 -0.988 ...
    ##  $ tBodyAccJerk-std()-Z       : num  -0.994 -0.992 -0.99 -0.993 -0.992 ...
    ##  $ tBodyGyro-std()-X          : num  -0.985 -0.983 -0.976 -0.991 -0.985 ...
    ##  $ tBodyGyro-std()-Y          : num  -0.977 -0.989 -0.994 -0.992 -0.992 ...
    ##  $ tBodyGyro-std()-Z          : num  -0.992 -0.989 -0.986 -0.988 -0.987 ...
    ##  $ tBodyGyroJerk-std()-X      : num  -0.992 -0.99 -0.988 -0.991 -0.991 ...
    ##  $ tBodyGyroJerk-std()-Y      : num  -0.993 -0.997 -0.996 -0.997 -0.996 ...
    ##  $ tBodyGyroJerk-std()-Z      : num  -0.992 -0.994 -0.992 -0.993 -0.995 ...
    ##  $ tBodyAccMag-std()          : num  -0.951 -0.976 -0.988 -0.986 -0.991 ...
    ##  $ tGravityAccMag-std()       : num  -0.951 -0.976 -0.988 -0.986 -0.991 ...
    ##  $ tBodyAccJerkMag-std()      : num  -0.994 -0.992 -0.99 -0.993 -0.996 ...
    ##  $ tBodyGyroMag-std()         : num  -0.964 -0.984 -0.986 -0.987 -0.989 ...
    ##  $ tBodyGyroJerkMag-std()     : num  -0.991 -0.996 -0.995 -0.995 -0.995 ...
    ##  $ fBodyAcc-std()-X           : num  -0.995 -0.999 -0.996 -0.996 -0.999 ...
    ##  $ fBodyAcc-std()-Y           : num  -0.983 -0.975 -0.966 -0.983 -0.98 ...
    ##  $ fBodyAcc-std()-Z           : num  -0.906 -0.955 -0.977 -0.99 -0.992 ...
    ##  $ fBodyAccJerk-std()-X       : num  -0.996 -0.997 -0.991 -0.991 -0.997 ...
    ##  $ fBodyAccJerk-std()-Y       : num  -0.991 -0.982 -0.981 -0.987 -0.989 ...
    ##  $ fBodyAccJerk-std()-Z       : num  -0.997 -0.993 -0.99 -0.994 -0.993 ...
    ##  $ fBodyGyro-std()-X          : num  -0.985 -0.985 -0.977 -0.993 -0.986 ...
    ##  $ fBodyGyro-std()-Y          : num  -0.974 -0.987 -0.993 -0.992 -0.992 ...
    ##  $ fBodyGyro-std()-Z          : num  -0.994 -0.99 -0.987 -0.989 -0.988 ...
    ##  $ fBodyAccMag-std()          : num  -0.956 -0.976 -0.989 -0.987 -0.99 ...
    ##  $ fBodyBodyAccJerkMag-std()  : num  -0.994 -0.992 -0.991 -0.992 -0.994 ...
    ##  $ fBodyBodyGyroMag-std()     : num  -0.961 -0.983 -0.986 -0.988 -0.989 ...
    ##  $ fBodyBodyGyroJerkMag-std() : num  -0.991 -0.996 -0.995 -0.995 -0.995 ...

### 2.4. Final tidy\_data

Final **'tidy\_data'** base contains 10299 obs. of 68 variables (2
factor variables and 66 numeric variables):

    ## [1] "RUN: str(tidy_data)"

    ## 'data.frame':    10299 obs. of  68 variables:
    ##  $ subject                    : Factor w/ 30 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ tBodyAcc-mean()-X          : num  0.289 0.278 0.28 0.279 0.277 ...
    ##  $ tBodyAcc-mean()-Y          : num  -0.0203 -0.0164 -0.0195 -0.0262 -0.0166 ...
    ##  $ tBodyAcc-mean()-Z          : num  -0.133 -0.124 -0.113 -0.123 -0.115 ...
    ##  $ tGravityAcc-mean()-X       : num  0.963 0.967 0.967 0.968 0.968 ...
    ##  $ tGravityAcc-mean()-Y       : num  -0.141 -0.142 -0.142 -0.144 -0.149 ...
    ##  $ tGravityAcc-mean()-Z       : num  0.1154 0.1094 0.1019 0.0999 0.0945 ...
    ##  $ tBodyAccJerk-mean()-X      : num  0.078 0.074 0.0736 0.0773 0.0734 ...
    ##  $ tBodyAccJerk-mean()-Y      : num  0.005 0.00577 0.0031 0.02006 0.01912 ...
    ##  $ tBodyAccJerk-mean()-Z      : num  -0.06783 0.02938 -0.00905 -0.00986 0.01678 ...
    ##  $ tBodyGyro-mean()-X         : num  -0.0061 -0.0161 -0.0317 -0.0434 -0.034 ...
    ##  $ tBodyGyro-mean()-Y         : num  -0.0314 -0.0839 -0.1023 -0.0914 -0.0747 ...
    ##  $ tBodyGyro-mean()-Z         : num  0.1077 0.1006 0.0961 0.0855 0.0774 ...
    ##  $ tBodyGyroJerk-mean()-X     : num  -0.0992 -0.1105 -0.1085 -0.0912 -0.0908 ...
    ##  $ tBodyGyroJerk-mean()-Y     : num  -0.0555 -0.0448 -0.0424 -0.0363 -0.0376 ...
    ##  $ tBodyGyroJerk-mean()-Z     : num  -0.062 -0.0592 -0.0558 -0.0605 -0.0583 ...
    ##  $ tBodyAccMag-mean()         : num  -0.959 -0.979 -0.984 -0.987 -0.993 ...
    ##  $ tGravityAccMag-mean()      : num  -0.959 -0.979 -0.984 -0.987 -0.993 ...
    ##  $ tBodyAccJerkMag-mean()     : num  -0.993 -0.991 -0.989 -0.993 -0.993 ...
    ##  $ tBodyGyroMag-mean()        : num  -0.969 -0.981 -0.976 -0.982 -0.985 ...
    ##  $ tBodyGyroJerkMag-mean()    : num  -0.994 -0.995 -0.993 -0.996 -0.996 ...
    ##  $ fBodyAcc-mean()-X          : num  -0.995 -0.997 -0.994 -0.995 -0.997 ...
    ##  $ fBodyAcc-mean()-Y          : num  -0.983 -0.977 -0.973 -0.984 -0.982 ...
    ##  $ fBodyAcc-mean()-Z          : num  -0.939 -0.974 -0.983 -0.991 -0.988 ...
    ##  $ fBodyAccJerk-mean()-X      : num  -0.992 -0.995 -0.991 -0.994 -0.996 ...
    ##  $ fBodyAccJerk-mean()-Y      : num  -0.987 -0.981 -0.982 -0.989 -0.989 ...
    ##  $ fBodyAccJerk-mean()-Z      : num  -0.99 -0.99 -0.988 -0.991 -0.991 ...
    ##  $ fBodyGyro-mean()-X         : num  -0.987 -0.977 -0.975 -0.987 -0.982 ...
    ##  $ fBodyGyro-mean()-Y         : num  -0.982 -0.993 -0.994 -0.994 -0.993 ...
    ##  $ fBodyGyro-mean()-Z         : num  -0.99 -0.99 -0.987 -0.987 -0.989 ...
    ##  $ fBodyAccMag-mean()         : num  -0.952 -0.981 -0.988 -0.988 -0.994 ...
    ##  $ fBodyBodyAccJerkMag-mean() : num  -0.994 -0.99 -0.989 -0.993 -0.996 ...
    ##  $ fBodyBodyGyroMag-mean()    : num  -0.98 -0.988 -0.989 -0.989 -0.991 ...
    ##  $ fBodyBodyGyroJerkMag-mean(): num  -0.992 -0.996 -0.995 -0.995 -0.995 ...
    ##  $ tBodyAcc-std()-X           : num  -0.995 -0.998 -0.995 -0.996 -0.998 ...
    ##  $ tBodyAcc-std()-Y           : num  -0.983 -0.975 -0.967 -0.983 -0.981 ...
    ##  $ tBodyAcc-std()-Z           : num  -0.914 -0.96 -0.979 -0.991 -0.99 ...
    ##  $ tGravityAcc-std()-X        : num  -0.985 -0.997 -1 -0.997 -0.998 ...
    ##  $ tGravityAcc-std()-Y        : num  -0.982 -0.989 -0.993 -0.981 -0.988 ...
    ##  $ tGravityAcc-std()-Z        : num  -0.878 -0.932 -0.993 -0.978 -0.979 ...
    ##  $ tBodyAccJerk-std()-X       : num  -0.994 -0.996 -0.991 -0.993 -0.996 ...
    ##  $ tBodyAccJerk-std()-Y       : num  -0.988 -0.981 -0.981 -0.988 -0.988 ...
    ##  $ tBodyAccJerk-std()-Z       : num  -0.994 -0.992 -0.99 -0.993 -0.992 ...
    ##  $ tBodyGyro-std()-X          : num  -0.985 -0.983 -0.976 -0.991 -0.985 ...
    ##  $ tBodyGyro-std()-Y          : num  -0.977 -0.989 -0.994 -0.992 -0.992 ...
    ##  $ tBodyGyro-std()-Z          : num  -0.992 -0.989 -0.986 -0.988 -0.987 ...
    ##  $ tBodyGyroJerk-std()-X      : num  -0.992 -0.99 -0.988 -0.991 -0.991 ...
    ##  $ tBodyGyroJerk-std()-Y      : num  -0.993 -0.997 -0.996 -0.997 -0.996 ...
    ##  $ tBodyGyroJerk-std()-Z      : num  -0.992 -0.994 -0.992 -0.993 -0.995 ...
    ##  $ tBodyAccMag-std()          : num  -0.951 -0.976 -0.988 -0.986 -0.991 ...
    ##  $ tGravityAccMag-std()       : num  -0.951 -0.976 -0.988 -0.986 -0.991 ...
    ##  $ tBodyAccJerkMag-std()      : num  -0.994 -0.992 -0.99 -0.993 -0.996 ...
    ##  $ tBodyGyroMag-std()         : num  -0.964 -0.984 -0.986 -0.987 -0.989 ...
    ##  $ tBodyGyroJerkMag-std()     : num  -0.991 -0.996 -0.995 -0.995 -0.995 ...
    ##  $ fBodyAcc-std()-X           : num  -0.995 -0.999 -0.996 -0.996 -0.999 ...
    ##  $ fBodyAcc-std()-Y           : num  -0.983 -0.975 -0.966 -0.983 -0.98 ...
    ##  $ fBodyAcc-std()-Z           : num  -0.906 -0.955 -0.977 -0.99 -0.992 ...
    ##  $ fBodyAccJerk-std()-X       : num  -0.996 -0.997 -0.991 -0.991 -0.997 ...
    ##  $ fBodyAccJerk-std()-Y       : num  -0.991 -0.982 -0.981 -0.987 -0.989 ...
    ##  $ fBodyAccJerk-std()-Z       : num  -0.997 -0.993 -0.99 -0.994 -0.993 ...
    ##  $ fBodyGyro-std()-X          : num  -0.985 -0.985 -0.977 -0.993 -0.986 ...
    ##  $ fBodyGyro-std()-Y          : num  -0.974 -0.987 -0.993 -0.992 -0.992 ...
    ##  $ fBodyGyro-std()-Z          : num  -0.994 -0.99 -0.987 -0.989 -0.988 ...
    ##  $ fBodyAccMag-std()          : num  -0.956 -0.976 -0.989 -0.987 -0.99 ...
    ##  $ fBodyBodyAccJerkMag-std()  : num  -0.994 -0.992 -0.991 -0.992 -0.994 ...
    ##  $ fBodyBodyGyroMag-std()     : num  -0.961 -0.983 -0.986 -0.988 -0.989 ...
    ##  $ fBodyBodyGyroJerkMag-std() : num  -0.991 -0.996 -0.995 -0.995 -0.995 ...
    ##  $ activity                   : Factor w/ 6 levels "LAYING","SITTING",..: 3 3 3 3 3 3 3 3 3 3 ...

3. INDEPENDENT TIDY DATASET: Average of each measurement variable by subject and activity
-----------------------------------------------------------------------------------------

### 3.1. Transformations made to the tidy\_data set

The **'tidy\_data'** set is **collapsed** into a new independent
database that summarizes the average of each measurement variable by
activity and subject called **'ind\_tidy\_data'**.

Also, variable names are modified: the word *average:* is added at the
beginning of each variable name (for measurement variables). In this
way, names are updated in order to give accurate information about which
kind of calculation is now shown by the summarized variables.

### 3.2. Variables

Besides the little transformation made to variable names (the word
*average:* is added at the beginning of each variable name), the
labeling structure of measurements variables is not modified. Further
information about variable names' components and structure can be found
in section 2.2.

These are the final **variables of the INDEPENDENT TIDY DATASET** stored
in the **'ind\_tidy\_data'** object:

    ## Warning: package 'plyr' was built under R version 3.3.3

    ## [1] "RUN: names(ind_tidy_data)"

    ##  [1] "activity"                            
    ##  [2] "subject"                             
    ##  [3] "average: tBodyAcc-mean()-X"          
    ##  [4] "average: tBodyAcc-mean()-Y"          
    ##  [5] "average: tBodyAcc-mean()-Z"          
    ##  [6] "average: tGravityAcc-mean()-X"       
    ##  [7] "average: tGravityAcc-mean()-Y"       
    ##  [8] "average: tGravityAcc-mean()-Z"       
    ##  [9] "average: tBodyAccJerk-mean()-X"      
    ## [10] "average: tBodyAccJerk-mean()-Y"      
    ## [11] "average: tBodyAccJerk-mean()-Z"      
    ## [12] "average: tBodyGyro-mean()-X"         
    ## [13] "average: tBodyGyro-mean()-Y"         
    ## [14] "average: tBodyGyro-mean()-Z"         
    ## [15] "average: tBodyGyroJerk-mean()-X"     
    ## [16] "average: tBodyGyroJerk-mean()-Y"     
    ## [17] "average: tBodyGyroJerk-mean()-Z"     
    ## [18] "average: tBodyAccMag-mean()"         
    ## [19] "average: tGravityAccMag-mean()"      
    ## [20] "average: tBodyAccJerkMag-mean()"     
    ## [21] "average: tBodyGyroMag-mean()"        
    ## [22] "average: tBodyGyroJerkMag-mean()"    
    ## [23] "average: fBodyAcc-mean()-X"          
    ## [24] "average: fBodyAcc-mean()-Y"          
    ## [25] "average: fBodyAcc-mean()-Z"          
    ## [26] "average: fBodyAccJerk-mean()-X"      
    ## [27] "average: fBodyAccJerk-mean()-Y"      
    ## [28] "average: fBodyAccJerk-mean()-Z"      
    ## [29] "average: fBodyGyro-mean()-X"         
    ## [30] "average: fBodyGyro-mean()-Y"         
    ## [31] "average: fBodyGyro-mean()-Z"         
    ## [32] "average: fBodyAccMag-mean()"         
    ## [33] "average: fBodyBodyAccJerkMag-mean()" 
    ## [34] "average: fBodyBodyGyroMag-mean()"    
    ## [35] "average: fBodyBodyGyroJerkMag-mean()"
    ## [36] "average: tBodyAcc-std()-X"           
    ## [37] "average: tBodyAcc-std()-Y"           
    ## [38] "average: tBodyAcc-std()-Z"           
    ## [39] "average: tGravityAcc-std()-X"        
    ## [40] "average: tGravityAcc-std()-Y"        
    ## [41] "average: tGravityAcc-std()-Z"        
    ## [42] "average: tBodyAccJerk-std()-X"       
    ## [43] "average: tBodyAccJerk-std()-Y"       
    ## [44] "average: tBodyAccJerk-std()-Z"       
    ## [45] "average: tBodyGyro-std()-X"          
    ## [46] "average: tBodyGyro-std()-Y"          
    ## [47] "average: tBodyGyro-std()-Z"          
    ## [48] "average: tBodyGyroJerk-std()-X"      
    ## [49] "average: tBodyGyroJerk-std()-Y"      
    ## [50] "average: tBodyGyroJerk-std()-Z"      
    ## [51] "average: tBodyAccMag-std()"          
    ## [52] "average: tGravityAccMag-std()"       
    ## [53] "average: tBodyAccJerkMag-std()"      
    ## [54] "average: tBodyGyroMag-std()"         
    ## [55] "average: tBodyGyroJerkMag-std()"     
    ## [56] "average: fBodyAcc-std()-X"           
    ## [57] "average: fBodyAcc-std()-Y"           
    ## [58] "average: fBodyAcc-std()-Z"           
    ## [59] "average: fBodyAccJerk-std()-X"       
    ## [60] "average: fBodyAccJerk-std()-Y"       
    ## [61] "average: fBodyAccJerk-std()-Z"       
    ## [62] "average: fBodyGyro-std()-X"          
    ## [63] "average: fBodyGyro-std()-Y"          
    ## [64] "average: fBodyGyro-std()-Z"          
    ## [65] "average: fBodyAccMag-std()"          
    ## [66] "average: fBodyBodyAccJerkMag-std()"  
    ## [67] "average: fBodyBodyGyroMag-std()"     
    ## [68] "average: fBodyBodyGyroJerkMag-std()"

### 3.3. Units

'subject' is a factor variable that identifies the subject who perfomed
the activity. The ID number ranges from 1 to 30.

    ## [1] "RUN: str(ind_tidy_data$subject)"

    ##  Factor w/ 30 levels "1","2","3","4",..: 1 2 3 4 5 6 7 8 9 10 ...

'activity' is a factor variable that identifies the activity performed
by each subject. It has 6 levels, 1 for each posible activity:

    ## [1] "RUN: str(ind_tidy_data$activity)"

    ##  Factor w/ 6 levels "LAYING","SITTING",..: 1 1 1 1 1 1 1 1 1 1 ...

    ## [1] "RUN: levels(ind_tidy_data$activity)"

    ## [1] "LAYING"             "SITTING"            "STANDING"          
    ## [4] "WALKING"            "WALKING_DOWNSTAIRS" "WALKING_UPSTAIRS"

The original units domain of the measurements variables were time (t-)
**s** and frequency (f-) **Hz**. Nevertheless, since the **data was
normalized** and bounded within \[-1,1\] from the **ORIGINAL DATASET**,
the units of measurement were eliminated at a first moment enabling
easily future comparation. In this way, all the measurement variables
are numeric:

    ## [1] "RUN: str(ind_tidy_data[2:67])"

    ## 'data.frame':    180 obs. of  66 variables:
    ##  $ subject                             : Factor w/ 30 levels "1","2","3","4",..: 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ average: tBodyAcc-mean()-X          : num  0.222 0.281 0.276 0.264 0.278 ...
    ##  $ average: tBodyAcc-mean()-Y          : num  -0.0405 -0.0182 -0.019 -0.015 -0.0183 ...
    ##  $ average: tBodyAcc-mean()-Z          : num  -0.113 -0.107 -0.101 -0.111 -0.108 ...
    ##  $ average: tGravityAcc-mean()-X       : num  -0.249 -0.51 -0.242 -0.421 -0.483 ...
    ##  $ average: tGravityAcc-mean()-Y       : num  0.706 0.753 0.837 0.915 0.955 ...
    ##  $ average: tGravityAcc-mean()-Z       : num  0.446 0.647 0.489 0.342 0.264 ...
    ##  $ average: tBodyAccJerk-mean()-X      : num  0.0811 0.0826 0.077 0.0934 0.0848 ...
    ##  $ average: tBodyAccJerk-mean()-Y      : num  0.00384 0.01225 0.0138 0.00693 0.00747 ...
    ##  $ average: tBodyAccJerk-mean()-Z      : num  0.01083 -0.0018 -0.00436 -0.00641 -0.00304 ...
    ##  $ average: tBodyGyro-mean()-X         : num  -0.01655 -0.01848 -0.02082 -0.00923 -0.02189 ...
    ##  $ average: tBodyGyro-mean()-Y         : num  -0.0645 -0.1118 -0.0719 -0.093 -0.0799 ...
    ##  $ average: tBodyGyro-mean()-Z         : num  0.149 0.145 0.138 0.17 0.16 ...
    ##  $ average: tBodyGyroJerk-mean()-X     : num  -0.107 -0.102 -0.1 -0.105 -0.102 ...
    ##  $ average: tBodyGyroJerk-mean()-Y     : num  -0.0415 -0.0359 -0.039 -0.0381 -0.0404 ...
    ##  $ average: tBodyGyroJerk-mean()-Z     : num  -0.0741 -0.0702 -0.0687 -0.0712 -0.0708 ...
    ##  $ average: tBodyAccMag-mean()         : num  -0.842 -0.977 -0.973 -0.955 -0.967 ...
    ##  $ average: tGravityAccMag-mean()      : num  -0.842 -0.977 -0.973 -0.955 -0.967 ...
    ##  $ average: tBodyAccJerkMag-mean()     : num  -0.954 -0.988 -0.979 -0.97 -0.98 ...
    ##  $ average: tBodyGyroMag-mean()        : num  -0.875 -0.95 -0.952 -0.93 -0.947 ...
    ##  $ average: tBodyGyroJerkMag-mean()    : num  -0.963 -0.992 -0.987 -0.985 -0.986 ...
    ##  $ average: fBodyAcc-mean()-X          : num  -0.939 -0.977 -0.981 -0.959 -0.969 ...
    ##  $ average: fBodyAcc-mean()-Y          : num  -0.867 -0.98 -0.961 -0.939 -0.965 ...
    ##  $ average: fBodyAcc-mean()-Z          : num  -0.883 -0.984 -0.968 -0.968 -0.977 ...
    ##  $ average: fBodyAccJerk-mean()-X      : num  -0.957 -0.986 -0.981 -0.979 -0.983 ...
    ##  $ average: fBodyAccJerk-mean()-Y      : num  -0.922 -0.983 -0.969 -0.944 -0.965 ...
    ##  $ average: fBodyAccJerk-mean()-Z      : num  -0.948 -0.986 -0.979 -0.975 -0.983 ...
    ##  $ average: fBodyGyro-mean()-X         : num  -0.85 -0.986 -0.97 -0.967 -0.976 ...
    ##  $ average: fBodyGyro-mean()-Y         : num  -0.952 -0.983 -0.978 -0.972 -0.978 ...
    ##  $ average: fBodyGyro-mean()-Z         : num  -0.909 -0.963 -0.962 -0.961 -0.963 ...
    ##  $ average: fBodyAccMag-mean()         : num  -0.862 -0.975 -0.966 -0.939 -0.962 ...
    ##  $ average: fBodyBodyAccJerkMag-mean() : num  -0.933 -0.985 -0.976 -0.962 -0.977 ...
    ##  $ average: fBodyBodyGyroMag-mean()    : num  -0.862 -0.972 -0.965 -0.962 -0.968 ...
    ##  $ average: fBodyBodyGyroJerkMag-mean(): num  -0.942 -0.99 -0.984 -0.984 -0.985 ...
    ##  $ average: tBodyAcc-std()-X           : num  -0.928 -0.974 -0.983 -0.954 -0.966 ...
    ##  $ average: tBodyAcc-std()-Y           : num  -0.837 -0.98 -0.962 -0.942 -0.969 ...
    ##  $ average: tBodyAcc-std()-Z           : num  -0.826 -0.984 -0.964 -0.963 -0.969 ...
    ##  $ average: tGravityAcc-std()-X        : num  -0.897 -0.959 -0.983 -0.921 -0.946 ...
    ##  $ average: tGravityAcc-std()-Y        : num  -0.908 -0.988 -0.981 -0.97 -0.986 ...
    ##  $ average: tGravityAcc-std()-Z        : num  -0.852 -0.984 -0.965 -0.976 -0.977 ...
    ##  $ average: tBodyAccJerk-std()-X       : num  -0.958 -0.986 -0.981 -0.978 -0.983 ...
    ##  $ average: tBodyAccJerk-std()-Y       : num  -0.924 -0.983 -0.969 -0.942 -0.965 ...
    ##  $ average: tBodyAccJerk-std()-Z       : num  -0.955 -0.988 -0.982 -0.979 -0.985 ...
    ##  $ average: tBodyGyro-std()-X          : num  -0.874 -0.988 -0.975 -0.973 -0.979 ...
    ##  $ average: tBodyGyro-std()-Y          : num  -0.951 -0.982 -0.977 -0.961 -0.977 ...
    ##  $ average: tBodyGyro-std()-Z          : num  -0.908 -0.96 -0.964 -0.962 -0.961 ...
    ##  $ average: tBodyGyroJerk-std()-X      : num  -0.919 -0.993 -0.98 -0.975 -0.983 ...
    ##  $ average: tBodyGyroJerk-std()-Y      : num  -0.968 -0.99 -0.987 -0.987 -0.984 ...
    ##  $ average: tBodyGyroJerk-std()-Z      : num  -0.958 -0.988 -0.983 -0.984 -0.99 ...
    ##  $ average: tBodyAccMag-std()          : num  -0.795 -0.973 -0.964 -0.931 -0.959 ...
    ##  $ average: tGravityAccMag-std()       : num  -0.795 -0.973 -0.964 -0.931 -0.959 ...
    ##  $ average: tBodyAccJerkMag-std()      : num  -0.928 -0.986 -0.976 -0.961 -0.977 ...
    ##  $ average: tBodyGyroMag-std()         : num  -0.819 -0.961 -0.954 -0.947 -0.958 ...
    ##  $ average: tBodyGyroJerkMag-std()     : num  -0.936 -0.99 -0.983 -0.983 -0.984 ...
    ##  $ average: fBodyAcc-std()-X           : num  -0.924 -0.973 -0.984 -0.952 -0.965 ...
    ##  $ average: fBodyAcc-std()-Y           : num  -0.834 -0.981 -0.964 -0.946 -0.973 ...
    ##  $ average: fBodyAcc-std()-Z           : num  -0.813 -0.985 -0.963 -0.962 -0.966 ...
    ##  $ average: fBodyAccJerk-std()-X       : num  -0.964 -0.987 -0.983 -0.98 -0.986 ...
    ##  $ average: fBodyAccJerk-std()-Y       : num  -0.932 -0.985 -0.971 -0.944 -0.966 ...
    ##  $ average: fBodyAccJerk-std()-Z       : num  -0.961 -0.989 -0.984 -0.98 -0.986 ...
    ##  $ average: fBodyGyro-std()-X          : num  -0.882 -0.989 -0.976 -0.975 -0.981 ...
    ##  $ average: fBodyGyro-std()-Y          : num  -0.951 -0.982 -0.977 -0.956 -0.977 ...
    ##  $ average: fBodyGyro-std()-Z          : num  -0.917 -0.963 -0.967 -0.966 -0.963 ...
    ##  $ average: fBodyAccMag-std()          : num  -0.798 -0.975 -0.968 -0.937 -0.963 ...
    ##  $ average: fBodyBodyAccJerkMag-std()  : num  -0.922 -0.985 -0.975 -0.958 -0.976 ...
    ##  $ average: fBodyBodyGyroMag-std()     : num  -0.824 -0.961 -0.955 -0.947 -0.959 ...

### 3.4. Final ind\_tidy\_data

Final **'ind\_tidy\_data'** base contains 180 obs. (30 subjects, each
one performing 6 different activities) of 68 variables (2 factor
variables and 66 numeric variables):

    ## [1] "RUN: str(ind_tidy_data)"

    ## 'data.frame':    180 obs. of  68 variables:
    ##  $ activity                            : Factor w/ 6 levels "LAYING","SITTING",..: 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ subject                             : Factor w/ 30 levels "1","2","3","4",..: 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ average: tBodyAcc-mean()-X          : num  0.222 0.281 0.276 0.264 0.278 ...
    ##  $ average: tBodyAcc-mean()-Y          : num  -0.0405 -0.0182 -0.019 -0.015 -0.0183 ...
    ##  $ average: tBodyAcc-mean()-Z          : num  -0.113 -0.107 -0.101 -0.111 -0.108 ...
    ##  $ average: tGravityAcc-mean()-X       : num  -0.249 -0.51 -0.242 -0.421 -0.483 ...
    ##  $ average: tGravityAcc-mean()-Y       : num  0.706 0.753 0.837 0.915 0.955 ...
    ##  $ average: tGravityAcc-mean()-Z       : num  0.446 0.647 0.489 0.342 0.264 ...
    ##  $ average: tBodyAccJerk-mean()-X      : num  0.0811 0.0826 0.077 0.0934 0.0848 ...
    ##  $ average: tBodyAccJerk-mean()-Y      : num  0.00384 0.01225 0.0138 0.00693 0.00747 ...
    ##  $ average: tBodyAccJerk-mean()-Z      : num  0.01083 -0.0018 -0.00436 -0.00641 -0.00304 ...
    ##  $ average: tBodyGyro-mean()-X         : num  -0.01655 -0.01848 -0.02082 -0.00923 -0.02189 ...
    ##  $ average: tBodyGyro-mean()-Y         : num  -0.0645 -0.1118 -0.0719 -0.093 -0.0799 ...
    ##  $ average: tBodyGyro-mean()-Z         : num  0.149 0.145 0.138 0.17 0.16 ...
    ##  $ average: tBodyGyroJerk-mean()-X     : num  -0.107 -0.102 -0.1 -0.105 -0.102 ...
    ##  $ average: tBodyGyroJerk-mean()-Y     : num  -0.0415 -0.0359 -0.039 -0.0381 -0.0404 ...
    ##  $ average: tBodyGyroJerk-mean()-Z     : num  -0.0741 -0.0702 -0.0687 -0.0712 -0.0708 ...
    ##  $ average: tBodyAccMag-mean()         : num  -0.842 -0.977 -0.973 -0.955 -0.967 ...
    ##  $ average: tGravityAccMag-mean()      : num  -0.842 -0.977 -0.973 -0.955 -0.967 ...
    ##  $ average: tBodyAccJerkMag-mean()     : num  -0.954 -0.988 -0.979 -0.97 -0.98 ...
    ##  $ average: tBodyGyroMag-mean()        : num  -0.875 -0.95 -0.952 -0.93 -0.947 ...
    ##  $ average: tBodyGyroJerkMag-mean()    : num  -0.963 -0.992 -0.987 -0.985 -0.986 ...
    ##  $ average: fBodyAcc-mean()-X          : num  -0.939 -0.977 -0.981 -0.959 -0.969 ...
    ##  $ average: fBodyAcc-mean()-Y          : num  -0.867 -0.98 -0.961 -0.939 -0.965 ...
    ##  $ average: fBodyAcc-mean()-Z          : num  -0.883 -0.984 -0.968 -0.968 -0.977 ...
    ##  $ average: fBodyAccJerk-mean()-X      : num  -0.957 -0.986 -0.981 -0.979 -0.983 ...
    ##  $ average: fBodyAccJerk-mean()-Y      : num  -0.922 -0.983 -0.969 -0.944 -0.965 ...
    ##  $ average: fBodyAccJerk-mean()-Z      : num  -0.948 -0.986 -0.979 -0.975 -0.983 ...
    ##  $ average: fBodyGyro-mean()-X         : num  -0.85 -0.986 -0.97 -0.967 -0.976 ...
    ##  $ average: fBodyGyro-mean()-Y         : num  -0.952 -0.983 -0.978 -0.972 -0.978 ...
    ##  $ average: fBodyGyro-mean()-Z         : num  -0.909 -0.963 -0.962 -0.961 -0.963 ...
    ##  $ average: fBodyAccMag-mean()         : num  -0.862 -0.975 -0.966 -0.939 -0.962 ...
    ##  $ average: fBodyBodyAccJerkMag-mean() : num  -0.933 -0.985 -0.976 -0.962 -0.977 ...
    ##  $ average: fBodyBodyGyroMag-mean()    : num  -0.862 -0.972 -0.965 -0.962 -0.968 ...
    ##  $ average: fBodyBodyGyroJerkMag-mean(): num  -0.942 -0.99 -0.984 -0.984 -0.985 ...
    ##  $ average: tBodyAcc-std()-X           : num  -0.928 -0.974 -0.983 -0.954 -0.966 ...
    ##  $ average: tBodyAcc-std()-Y           : num  -0.837 -0.98 -0.962 -0.942 -0.969 ...
    ##  $ average: tBodyAcc-std()-Z           : num  -0.826 -0.984 -0.964 -0.963 -0.969 ...
    ##  $ average: tGravityAcc-std()-X        : num  -0.897 -0.959 -0.983 -0.921 -0.946 ...
    ##  $ average: tGravityAcc-std()-Y        : num  -0.908 -0.988 -0.981 -0.97 -0.986 ...
    ##  $ average: tGravityAcc-std()-Z        : num  -0.852 -0.984 -0.965 -0.976 -0.977 ...
    ##  $ average: tBodyAccJerk-std()-X       : num  -0.958 -0.986 -0.981 -0.978 -0.983 ...
    ##  $ average: tBodyAccJerk-std()-Y       : num  -0.924 -0.983 -0.969 -0.942 -0.965 ...
    ##  $ average: tBodyAccJerk-std()-Z       : num  -0.955 -0.988 -0.982 -0.979 -0.985 ...
    ##  $ average: tBodyGyro-std()-X          : num  -0.874 -0.988 -0.975 -0.973 -0.979 ...
    ##  $ average: tBodyGyro-std()-Y          : num  -0.951 -0.982 -0.977 -0.961 -0.977 ...
    ##  $ average: tBodyGyro-std()-Z          : num  -0.908 -0.96 -0.964 -0.962 -0.961 ...
    ##  $ average: tBodyGyroJerk-std()-X      : num  -0.919 -0.993 -0.98 -0.975 -0.983 ...
    ##  $ average: tBodyGyroJerk-std()-Y      : num  -0.968 -0.99 -0.987 -0.987 -0.984 ...
    ##  $ average: tBodyGyroJerk-std()-Z      : num  -0.958 -0.988 -0.983 -0.984 -0.99 ...
    ##  $ average: tBodyAccMag-std()          : num  -0.795 -0.973 -0.964 -0.931 -0.959 ...
    ##  $ average: tGravityAccMag-std()       : num  -0.795 -0.973 -0.964 -0.931 -0.959 ...
    ##  $ average: tBodyAccJerkMag-std()      : num  -0.928 -0.986 -0.976 -0.961 -0.977 ...
    ##  $ average: tBodyGyroMag-std()         : num  -0.819 -0.961 -0.954 -0.947 -0.958 ...
    ##  $ average: tBodyGyroJerkMag-std()     : num  -0.936 -0.99 -0.983 -0.983 -0.984 ...
    ##  $ average: fBodyAcc-std()-X           : num  -0.924 -0.973 -0.984 -0.952 -0.965 ...
    ##  $ average: fBodyAcc-std()-Y           : num  -0.834 -0.981 -0.964 -0.946 -0.973 ...
    ##  $ average: fBodyAcc-std()-Z           : num  -0.813 -0.985 -0.963 -0.962 -0.966 ...
    ##  $ average: fBodyAccJerk-std()-X       : num  -0.964 -0.987 -0.983 -0.98 -0.986 ...
    ##  $ average: fBodyAccJerk-std()-Y       : num  -0.932 -0.985 -0.971 -0.944 -0.966 ...
    ##  $ average: fBodyAccJerk-std()-Z       : num  -0.961 -0.989 -0.984 -0.98 -0.986 ...
    ##  $ average: fBodyGyro-std()-X          : num  -0.882 -0.989 -0.976 -0.975 -0.981 ...
    ##  $ average: fBodyGyro-std()-Y          : num  -0.951 -0.982 -0.977 -0.956 -0.977 ...
    ##  $ average: fBodyGyro-std()-Z          : num  -0.917 -0.963 -0.967 -0.966 -0.963 ...
    ##  $ average: fBodyAccMag-std()          : num  -0.798 -0.975 -0.968 -0.937 -0.963 ...
    ##  $ average: fBodyBodyAccJerkMag-std()  : num  -0.922 -0.985 -0.975 -0.958 -0.976 ...
    ##  $ average: fBodyBodyGyroMag-std()     : num  -0.824 -0.961 -0.955 -0.947 -0.959 ...
    ##  $ average: fBodyBodyGyroJerkMag-std() : num  -0.933 -0.989 -0.983 -0.983 -0.983 ...

4. FOR MORE INFORMATION
-----------------------

For more information about 'tidy\_data' and 'ind\_tidy\_data' sets
contact: <https://github.com/AnaMJaimeR/>
